source_en/ImplementationAtEachLayer/DomainLayer.rst
Please review #2009 .
(cherry picked from commit 92ffab959a16f1e2215b99cc924ccd1a1e45597e)
=> [5.2.x]#2009 @transaction not used while using MyBatis3.3

source_en/ImplementationAtEachLayer/DomainLayer.rst
Please review #2009 .
(cherry picked from commit 92ffab959a16f1e2215b99cc924ccd1a1e45597e)
=> [5.1.x]#2009 @transaction not used while using MyBatis3.3

source_en/Tutorial/TutorialTodo.rst
Please review #2019 .
(cherry picked from commit aea848abdd8078db19ca7bad0bc2003bfa272edf)
=> [5.2.x]#2019 Improved guideline for Todo application tutorial

source_en/Tutorial/TutorialTodo.rst
Please review #2019 .
(cherry picked from commit aea848abdd8078db19ca7bad0bc2003bfa272edf)
=> [5.3.x]#2019 Improved guideline for Todo application tutorial

source_en/ArchitectureInDetail/Validation.rst
Please review #1927 .
(cherry picked from commit 26b04c2a52882277975bbc0f019237f0c7d8e6e4)
=> [5.1.x]Translation of the Date and time format validation #1927

source_en/ArchitectureInDetail/Validation.rst
Please review #1927 .
(cherry picked from commit 26b04c2a52882277975bbc0f019237f0c7d8e6e4)
=> [translation/5.1.1]Translation of the Date and time format validation #1927

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst
Please review #1911 .
(cherry picked from commit 0a71a8455049d63e673bbc2775548b0734c72962)
=> [translation/5.1.1]Translation of addition of string2 dependency #1911

source_en/TutorialTodo/index.rst
Please review #2019 .
cherry-pick aea848abdd8078db19ca7bad0bc2003bfa272edf and solved conflict.
=> [5.1.x]#2019 Improved guideline for Todo application tutorial

source_en/TutorialTodo/index.rst
Please review #2019 .
cherry-pick aea848abdd8078db19ca7bad0bc2003bfa272edf and solved conflict.
=> [translation/5.1.1]#2019 Improved guideline for Todo application tutorial

README.md
Please review #1869.
The badge extension is change to svg from png.
=> The badge extension is change to svg. #1869

README.md
Please review #1869.
The badge extension is change to svg from png.
(cherry picked from commit f9bb74df600ed154289403a8d73070a9ee983980)
=> [5.2.x] The badge extension is change to svg. #1869

README.md
Please review #XXX.
The badge extension is change to svg from png.
(cherry picked from commit f9bb74df600ed154289403a8d73070a9ee983980)
=> [5.1.x] The badge extension is change to svg. #1869

README.md
Please review #1869.
The badge extension is change to svg from png.
(cherry picked from commit f9bb74df600ed154289403a8d73070a9ee983980)
=> [5.0.x] The badge extension is change to svg. #1869

source_en/ArchitectureInDetail/GeneralFuncDetail/Logging.rst, source_en/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source_en/Introduction/ChangeLog.rst
=> #1940 Added how to extend to the logging section

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> #2003 Description for ValidationMessages.properties corrected

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/Dozer.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source_en/Introduction/ChangeLog.rst, source_en/Overview/FrameworkStack.rst
=> #2024 Added to JSR310 corresponding guidelines of MyBatis and Jackson

source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/Introduction/ChangeLog.rst
=> #2040 HTTP response header modified

source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst
=> @2065 Added status code at the time of web service

source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst
=> #1899 Changed HTTP Proxy Server Setting in RestClient

source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/Introduction/ChangeLog.rst
=> #2121 Added measures against directory traversal attack

source_en/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst, source_en/Introduction/ChangeLog.rst
=> #2065 Removed TransactionTokenContext description

source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/Introduction/ChangeLog.rst
=> #2070 Added warnings for new vulnerabilities in commons file upload

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/Introduction/ChangeLog.rst
=> 1980 Added description for customization of JISX codepoints

README.md
=> fix travis-ci badge in README.md on 5.2.x #2199

README.md
=> fix travis-ci badge in README.md on 5.1.x #2199

source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst
=> [5.2.x] #1899 Changed HTTP Proxy Server Setting in RestClient

source_en/ArchitectureInDetail/RestClient.rst
=> [translation/5.1.1] #1899 Changed HTTP Proxy Server Setting in RestClient

source_en/ArchitectureInDetail/RestClient.rst
=> [5.1.x] #1899 Changed HTTP Proxy Server Setting in RestClient

source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst
=> [5.3.x] #1899 Changed HTTP Proxy Server Setting in RestClient

source_en/ArchitectureInDetail/GeneralFuncDetail/Logging.rst, source_en/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source_en/Introduction/ChangeLog.rst
=> [5.2.x] #1940 Added how to extend to the logging section

source_en/ArchitectureInDetail/GeneralFuncDetail/Logging.rst, source_en/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source_en/Introduction/ChangeLog.rst
=> [5.3.x] #1940 Added how to extend to the logging section

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/Introduction/ChangeLog.rst
Please review #1980.
(cherry picked from commit 73c49e84890c35eb4b6292a3275950781f240ce4)
=> [5.2.x] 1980 Added description for customization of JISX codepoints

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst, source_en/Introduction/ChangeLog.rst
Please review #1980.
(cherry picked from commit 73c49e84890c35eb4b6292a3275950781f240ce4)
=> [translation/5.1.1] 1980 Added description for customization of JISX codepoints

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst, source_en/Introduction/ChangeLog.rst
Please review #1980.
(cherry picked from commit 73c49e84890c35eb4b6292a3275950781f240ce4)
=> [5.1.x] Issues/#1980 added description for customization of jisx codepoints 5.1.x

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/Introduction/ChangeLog.rst
Please review #1980.
(cherry picked from commit 73c49e84890c35eb4b6292a3275950781f240ce4)
=> [5.3.x] 1980 Added description for customization of JISX codepoints

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
Please review #2003.
(cherry picked from commit 650715f1dd9ba03ee5c9efcea54c5720906adca8)
=> [5.2.x] #2003 Description for ValidationMessages.properties corrected

source_en/ArchitectureInDetail/Validation.rst
Please review #2003.
(cherry picked from commit 650715f1dd9ba03ee5c9efcea54c5720906adca8)
=> [translation/5.1.1] #2003 Description for ValidationMessages.properties corrected

source_en/ArchitectureInDetail/Validation.rst
Please review #2003.
(cherry picked from commit 650715f1dd9ba03ee5c9efcea54c5720906adca8)
=> [5.1.x] #2003 Description for ValidationMessages.properties corrected

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
Please review #2048.
(cherry picked from commit 57daf9626bba66bb9bbc487b5f47d6d0cff6f30a)
=> [5.2.x] #2048 Added warning of method validation

source_en/ArchitectureInDetail/Validation.rst
Please review #2048.
(cherry picked from commit 57daf9626bba66bb9bbc487b5f47d6d0cff6f30a)
=> [translation/5.1.1] #2048 Added warning of method validation

source_en/ArchitectureInDetail/Validation.rst
Please review #2048.
(cherry picked from commit 57daf9626bba66bb9bbc487b5f47d6d0cff6f30a)
=> [5.1.x] #2048 Added warning of method validation

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
Please review #2048.
(cherry picked from commit 57daf9626bba66bb9bbc487b5f47d6d0cff6f30a)
=> [5.3.x] #2048 Added warning of method validation

source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst
Please review #2065.
(cherry picked from commit f91fcaec2dfef2c3696d8639f03932ff8caadffd)
=> [5.2.x] @2065 Added status code at the time of web service

source_en/ArchitectureInDetail/SOAP.rst
Please review #2065.
(cherry picked from commit f91fcaec2dfef2c3696d8639f03932ff8caadffd)
=> [translation/5.1.1] @2065 Added status code at the time of web service

source_en/ArchitectureInDetail/SOAP.rst
Please review #2065.
(cherry picked from commit f91fcaec2dfef2c3696d8639f03932ff8caadffd)
=> [5.1.x] @2065 Added status code at the time of web service

source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst
Please review #2065.
(cherry picked from commit f91fcaec2dfef2c3696d8639f03932ff8caadffd)
=> [5.3.x] @2065 Added status code at the time of web service

source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/Introduction/ChangeLog.rst
Please review #2121.
(cherry picked from commit b731c3100cbcfc1ecf7f231c5dd465ab2bbeb37e)
=> [5.2.x] #2121 Added measures against directory traversal attack

source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/Introduction/ChangeLog.rst
Please review #2121.
(cherry picked from commit b731c3100cbcfc1ecf7f231c5dd465ab2bbeb37e)
=> [5.3.x] #2121 Added measures against directory traversal attack

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst
=> Description of SOAP Web Service exception handling is not kind for developers[5.2.x].#1881.

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/Dozer.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source_en/Introduction/ChangeLog.rst, source_en/Overview/FrameworkStack.rst
Please review #2024.
rebase https://github.com/terasolunaorg/guideline/pull/2229
=> [5.2.x] #2024 Added to JSR310 corresponding guidelines of MyBatis and Jackson

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/Dozer.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source_en/Introduction/ChangeLog.rst, source_en/Overview/FrameworkStack.rst
Please review #2024.
rebase https://github.com/terasolunaorg/guideline/pull/2230
=> [5.3.x] #2024 Added to JSR310 corresponding guidelines of MyBatis and Jackson

source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/Introduction/ChangeLog.rst
Please review #2040.
rebase https://github.com/terasolunaorg/guideline/pull/2231
=> [5.2.x] #2040 HTTP response header modified

source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/Introduction/ChangeLog.rst
Please review #2040.
rebase https://github.com/terasolunaorg/guideline/pull/2232
=> [5.3.x] #2040 HTTP response header modified

source_en/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst, source_en/Introduction/ChangeLog.rst
Please review #2069.
rebase https://github.com/terasolunaorg/guideline/pull/2249
=> [5.2.x] #2069 Removed TransactionTokenContext description

source_en/ArchitectureInDetail/DoubleSubmitProtection.rst, source_en/Introduction/ChangeLog.rst
Please review #2069.
rebase https://github.com/terasolunaorg/guideline/pull/2250
=> [translation/5.1.1] #2069 Removed TransactionTokenContext description

source_en/ArchitectureInDetail/DoubleSubmitProtection.rst, source_en/Introduction/ChangeLog.rst
Please review #2069.
rebase https://github.com/terasolunaorg/guideline/pull/2251
=> [5.1.x] #2069 Removed TransactionTokenContext description

source_en/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst, source_en/Introduction/ChangeLog.rst
Please review #2069.
rebase https://github.com/terasolunaorg/guideline/pull/2252
=> [5.3.x] #2069 Removed TransactionTokenContext description

source_en/ArchitectureInDetail/FileUpload.rst, source_en/Introduction/ChangeLog.rst
Please review #2070 .
rebase https://github.com/terasolunaorg/guideline/pull/2254
(cherry picked from commit feeea2f8bd8f9e95489ae73a6868f4957f6a8709)
=> [translation/5.1.1] #2070 Added warnings for new vulnerabilities in commons file upload

source_en/ArchitectureInDetail/FileUpload.rst, source_en/Introduction/ChangeLog.rst
Please review #2070.
rebase https://github.com/terasolunaorg/guideline/pull/2255
(cherry picked from commit feeea2f8bd8f9e95489ae73a6868f4957f6a8709)
=> [5.1.x] #2070 Added warnings for new vulnerabilities in commons file upload

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> 1981 Added warning about validation of string for surrogate pair

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> #2041 Added description of highlight when crossfield validation fails

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> [5.2.x] 1981 Added warning about validation of string for surrogate pair

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst, source_en/ArchitectureInDetail/Validation.rst
=> [translation/5.1.1] 1981 Added warning about validation of string for surrogate pair

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst, source_en/ArchitectureInDetail/Validation.rst
=> [5.1.x] 1981 Added warning about validation of string for surrogate pair

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> [5.3.x] 1981 Added warning about validation of string for surrogate pair

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> [5.2.x] #2041 Added description of highlight when crossfield validation fails

source_en/ArchitectureInDetail/Validation.rst
=> [translation/5.1.1] #2041 Added description of highlight when crossfield validation fails

source_en/ArchitectureInDetail/Validation.rst
Please review #2041.
(cherry picked from commit 37eb6c295607e1f8cf041d14a0ea8774593a709a)
=> [5.1.x] #2041 Added description of highlight when crossfield validation fails

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
Please review #2041.
(cherry picked from commit 37eb6c295607e1f8cf041d14a0ea8774593a709a)
=> [5.3.x] #2041 Added description of highlight when crossfield validation fails

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/SystemDate.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Pagination.rst, source_en/ImplementationAtEachLayer/DomainLayer.rst, source_en/Overview/FrameworkStack.rst
=> modify table width. #2133

source_en/Introduction/ChangeLog.rst
Please review #2128.
rebase https://github.com/terasolunaorg/guideline/pull/2276
=> #2128 Added change logs for 5.2.0

source_en/Introduction/ChangeLog.rst
=> [5.2.x] Added change logs for 5.2.0 #2128

source_en/Introduction/ChangeLog.rst
=> [translation/1.0.5] Added change logs for 1.0.5 #2130

source_en/Introduction/ChangeLog.rst
=> Added change logs for 1.0.5 #2130

source_en/ArchitectureInDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/Pagination.rst, source_en/ArchitectureInDetail/SystemDate.rst, source_en/ImplementationAtEachLayer/DomainLayer.rst
=> [translation/1.0.5] modify table width. #2133

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/SystemDate.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Pagination.rst, source_en/ImplementationAtEachLayer/DomainLayer.rst, source_en/Overview/FrameworkStack.rst
=> [5.3.x] modify table width. #2133

source_en/Introduction/ChangeLog.rst
=> [5.3.x] Added change logs for 5.2.0 #2128

source_en/Introduction/ChangeLog.rst
=> [translation5.1.1] Added change logs for 5.1.1 #2129

source_en/Introduction/ChangeLog.rst
=> Added change logs for 5.1.1 #2129

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> [translation/5.2.0] fix reference path. #2307

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> [5.2.x] fix reference path. #2307

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst, source_en/ArchitectureInDetail/Validation.rst
=> [translation/5.1.1] fix reference path. #2307

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst, source_en/ArchitectureInDetail/Validation.rst
=> [5.1.x] fix reference path. #2307

source_en/Introduction/CriteriaBasedMapping.rst
=> [translation/5.1.1] add more link to security mapping table #2132

source_en/Introduction/CriteriaBasedMapping.rst
=> [5.1.x] add more link to security mapping table #2132

source_en/Introduction/CriteriaBasedMapping.rst
=> [translation/5.2.0] add more link to security mapping table #2132

source_en/Introduction/CriteriaBasedMapping.rst
=> [5.2.x] add more link to security mapping table #2132

source_en/Introduction/CriteriaBasedMapping.rst
=> [5.3.x] add more link to security mapping table #2132

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> Update short version to 1.0.5 #2191

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/SpringSecurity.rst, source/Tutorial/TutorialREST.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialSession.rst, source/Tutorial/TutorialTodo.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Security/SpringSecurity.rst, source_en/Tutorial/TutorialREST.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialSession.rst, source_en/Tutorial/TutorialTodo.rst
=> [5.3.x] modified reflect the change of blank projects #2081

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/SpringSecurity.rst, source/Tutorial/TutorialREST.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialSession.rst, source/Tutorial/TutorialTodo.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Security/SpringSecurity.rst, source_en/Tutorial/TutorialREST.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialSession.rst, source_en/Tutorial/TutorialTodo.rst
Please review #2081 .
(cherry picked from commit 11f026e64982c72a4c8644a0306305b878bbda45)
=> [5.2.x] update reflect the change of blank projects #2081

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/SpringSecurity.rst, source/Security/Tutorial.rst, source/TutorialREST/index.rst, source/TutorialSession/index.rst, source/TutorialTodo/index.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Security/SpringSecurity.rst, source_en/Security/Tutorial.rst, source_en/TutorialREST/index.rst, source_en/TutorialSession/index.rst, source_en/TutorialTodo/index.rst
=> [5.1.x] modified reflect the change of blank projects #2081

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/Tutorial.rst, source/TutorialREST/index.rst, source/TutorialTodo/index.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Security/Tutorial.rst, source_en/TutorialREST/index.rst, source_en/TutorialTodo/index.rst
=> [5.0.x] modified reflect the change of blank projects #2081

source/Appendix/CreateProjectFromBlank.rst, source/Overview/FirstApplication.rst, source/Security/Tutorial.rst, source/TutorialREST/index.rst, source/TutorialTodo/index.rst
=> [1.0.x] modified reflect the change of blank projects #2081

source/ArchitectureInDetail/MessagingDetail/Email.rst, source/ArchitectureInDetail/MessagingDetail/JMS.rst, source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst, source/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst, source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FrameworkStack.rst
Please review #2189 .
The content of the comment was corrected .
=> a table not delivered to one page of pdf #2189

source/ArchitectureInDetail/MessagingDetail/Email.rst, source/ArchitectureInDetail/MessagingDetail/JMS.rst, source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst, source/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst, source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FrameworkStack.rst
Please review #2189 .
The content of the comment was corrected .
=> a table not delivered to one page of pdf 5.2.x #2189 

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
=> Changed Guideline for TypeHandler in MyBatis_3.4. #1775

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst
Please review #2260 .
https://docs.jboss.org/hibernate/validator/5.2/api/org/hibernate/validator/constraints/URL.html
http://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html/ch07.html
=> Modify description for @URL.#2260

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> 「4.1.2.3.1. Spring Validatorによる相関項目チェック実装」の誤記  #2397 

source/ImplementationAtEachLayer/ApplicationLayer.rst, source/Introduction/ChangeLog.rst, source/Security/Authentication.rst
=> added description and change logs of view-controller for spring 4.3. #2371

source/Security/LinkageWithBrowser.rst
=> support content security policy. #2400

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
=> Update JDBC Jar version for postgresql  #2405

source/ImplementationAtEachLayer/DomainLayer.rst
Please review ##2219 (backport for 5.2.x).
=> AbstractBLogic structure prevents a creation of proxy class that may lead AOP disabled or mis-injection  #2219 (backport for 5.2.x)

source/ImplementationAtEachLayer/DomainLayer.rst
Please review #2219 (backport for 1.0.x)
=> AbstractBLogic structure prevents a creation of proxy class that may lead AOP disabled or mis-injection #2219 (backport for 1.0.x)

source/ImplementationAtEachLayer/DomainLayer.rst
Please review #2219 (backport for 5.0.x)
=> AbstractBLogic structure prevents a creation of proxy class that may lead AOP disabled or mis-injection #2219 (backport for 5.0.x)

source/ImplementationAtEachLayer/DomainLayer.rst
Please review #2219 (backport for 5.1.x)
=> AbstractBLogic structure prevents a creation of proxy class that may lead AOP disabled or mis-injection #2219 (backport for 5.1.x)

source/Overview/FirstApplication.rst, source/Tutorial/TutorialREST.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst, source_en/Overview/FirstApplication.rst, source_en/Tutorial/TutorialREST.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialTodo.rst
=> fix typo in sample of spring-mvc.xml. #2410

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
=> add explanation for AsyncRequestTimeoutException. #2271

source/Introduction/ChangeLog.rst
=> modify changelog. #2369

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
=> [5.2.x]add description for warning when access restriction to specific URL,add change log

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
=> [1.0.x]add description for warning when access restriction to specific URL,add change log

source/Security/Authorization.rst
:emphasize-lines: 2,3 の除去1.0.x対応版です。
=> [1.0.x]remove highlighting in spring-security.xml for authorization.#2399

source/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst, source/ArchitectureInDetail/DataAccessDetail/ExclusionControl.rst, source/Introduction/ChangeLog.rst
=> Add warning for nowait issue on PostgreSQL + Hibernate 5.0 #2372

source_en/Introduction/ChangeLog.rst, source_en/Tutorial/TutorialTodo.rst
=> correct mapping between field and column name for English.#2476

source_en/ArchitectureInDetail/MessagingDetail/JMS.rst
Please review #2153 .
Fix for english version.
=> Typo in JMS section.  #2153 

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
=> excludedExceptions set to array #2368

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
=> Removed incorrect wording.#2470

source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst
=> fix context route to context root #2490

source/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst
Please review #2480.
I have verified the code which can download following file.
=> fix misdescroption in chapter of downloading excel file #2480

source/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst
Please review #2480.
cherry picked from commit 716024a635e96032f06533e3d0adcb534383769b a7d208bf5c20fe77d6e69699a7dc149286071ea8 880f180a7dc7e0f0abd89395c9a5a52f7e61fad1
=> fix misdescroption in chapter of downloading excel file 5.2.x #2480 

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Introduction/ChangeLog.rst, source_en/Overview/FirstApplication.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialTodo.rst
Please review #2444 .
日本語版と英語版をまとめております。
=> [5.3.x] remove maven option '-DarchetypeCatalog',modified maven option '-DarchetypeVersion' to '5.3.0.RELEASE'

source/Introduction/ChangeLog.rst, source/Security/Authentication.rst
=> fix Warning of when using SecureRandom #2177

source/Introduction/ChangeLog.rst, source/Security/Authentication.rst
=> [5.2.x] fix Warning of when using SecureRandom #2177

source/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source/ArchitectureInDetail/MessagingDetail/Email.rst, source/ArchitectureInDetail/MessagingDetail/JMS.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/ArchitectureInDetail/WebServiceDetail/SOAP.rst
Please review #2403.
I have added the links to JBoss7 documents based on JBoss6.4 and the explaneation how to avoid garbled text when the files uploading.
=> Support JBoss7 #2403

source/Introduction/ChangeLog.rst, source/Overview/FrameworkStack.rst
=> [5.3.x]Update new OSS stacks

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
=> [5.0.x]add description for warning when access restriction to specific URL.

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
=> [5.1.x]add description for warning when access restriction to specific URL.

source/Security/Authorization.rst
=> [1.0.x]Modified version of spring framework to 3.2.18.#2525

source/Introduction/ChangeLog.rst, source/Overview/FrameworkStack.rst
=> [1.0.x]Update new OSS stacks

source/Security/Authorization.rst
=> [5.3.x]Modify Description for way to avoid CVE-2016-5007 #2525

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst
=> [5.2.x]Build fails with "mvn archetype:generate"#2523

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Security/Tutorial.rst, source/TutorialTodo/index.rst
=> [5.1.x]Build fails with "mvn archetype:generate"#2523

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Security/Tutorial.rst, source/TutorialTodo/index.rst
=> [5.0.x]Build fails with "mvn archetype:generate"#2523

source/Appendix/CreateProjectFromBlank.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Security/Tutorial.rst, source/TutorialREST/index.rst, source/TutorialTodo/index.rst
=> [1.0.x]Build fails with "mvn archetype:generate"#2523

source/TutorialREST/index.rst
Please review https://github.com/terasolunaorg/guideline/issues/2523#issuecomment-282187217 .
=> Correct woring directory path in TutorialREST/index.rst.#2523

source/ImplementationAtEachLayer/ApplicationLayer.rst, source/Introduction/ChangeLog.rst
=> [5.3.0]due to the upgrading of dependency library version,misdescription has occured

source/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source/ArchitectureInDetail/MessagingDetail/Email.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateProject.rst
=> support tomcat8.5 #2518

source/Introduction/ChangeLog.rst
Please review #2518 #2533 .
I add ChangeLog for #2533 correspondence
=> add ChangeLog for #2533 correspondence #2518

source_en/Appendix/Nexus.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/Logging.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/PropertyManagement.rst, source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/ArchitectureInDetail/MessagingDetail/JMS.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Codelist.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source_en/ImplementationAtEachLayer/ApplicationLayer.rst, source_en/ImplementationAtEachLayer/CreateProject.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/ImplementationAtEachLayer/DomainLayer.rst, source_en/Overview/FirstApplication.rst, source_en/Overview/FrameworkStack.rst, source_en/Overview/SpringMVCOverview.rst, source_en/Security/Authentication.rst, source_en/Security/Authorization.rst, source_en/Security/Encryption.rst, source_en/Security/LinkageWithBrowser.rst, source_en/Security/SecureLoginDemo.rst, source_en/Security/SpringSecurity.rst, source_en/Tutorial/TutorialTodo.rst
=> check version for 2017 winter en #2532

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py, source/ImplementationAtEachLayer/CreateProject.rst
Please review.
Update copyright(#2549) and resolve warning (#2118).
=> update copyright 2017 #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py, source/ImplementationAtEachLayer/CreateProject.rst
Please review.
Update copyright(#2549) and resolve warning (#2118).
=> [5.2.x] update copyright 2017 #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> [5.1.x] update copyright 2017 #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> [5.0.x] update copyright 2017 #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> [1.0.x] update copyright 2017 #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> change corporate name to NTT DATA Corporation #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
(cherry picked from commit 2df94f1936006ab4d2d00f9c5593415d9c8902c1)
Please review #2549.
=> [5.2.x] change corporate name to NTT DATA Corporation #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
(cherry picked from commit 2df94f1936006ab4d2d00f9c5593415d9c8902c1)
Please review #2549.
=> [5.1.x] change corporate name to NTT DATA Corporation #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
(cherry picked from commit 2df94f1936006ab4d2d00f9c5593415d9c8902c1)
Please review #2549.
=> [5.0.x] change corporate name to NTT DATA Corporation #2549

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> [1.0.x] change corporate name to NTT DATA Corporation #2549

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst
=> Update check broken or old link. #2453

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst
Please review #2453.
Backport for 5.2.x.
=> 【5.2.x】Update check broken or old link. #2453

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
=> [5.3.x]Fix description on CVE-2016-5007.#2565

source/Introduction/ChangeLog.rst
=> Add change logs for 5.3.0.#2519

source/Introduction/ChangeLog.rst
=> Add change logs for 5.2.1.#2520

source/Introduction/ChangeLog.rst
=> Add change logs for 1.0.6.#2521

source/Security/Authorization.rst
Please review #2525 .
https://github.com/terasolunaorg/guideline/issues/2525#issuecomment-282932690
のコメント対応5.2.x版です。
=> [5.2.x]Modify Description for way to avoid CVE-2016-5007 #2525

source/Security/Authorization.rst
Please review #2525 .
https://github.com/terasolunaorg/guideline/issues/2525#issuecomment-282929628
のコメント対応PRです。
=> [1.0.x]Modify Description for way to avoid CVE-2016-5007 #2525

source/Security/Authorization.rst
Please review #2525 .
PR #2592 の5.0.x版バックポートです。
=> [5.0.x]Modify Description for way to avoid CVE-2016-5007 #2525

source_en/Appendix/EnvironmentIndependency.rst, source_en/Appendix/Nexus.rst, source_en/Appendix/ProjectStructureStandard.rst, source_en/Appendix/TagLibAndELFunctions.rst, source_en/ArchitectureInDetail/Codelist.rst, source_en/ArchitectureInDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/DataAccessJpa.rst, source_en/ArchitectureInDetail/FileDownload.rst, source_en/ArchitectureInDetail/FileUpload.rst, source_en/ArchitectureInDetail/PropertyManagement.rst, source_en/ArchitectureInDetail/Validation.rst, source_en/ImplementationAtEachLayer/ApplicationLayer.rst, source_en/ImplementationAtEachLayer/DomainLayer.rst, source_en/Overview/ApplicationLayering.rst, source_en/Overview/FirstApplication.rst, source_en/Overview/SpringMVCOverview.rst, source_en/Security/Authorization.rst, source_en/TutorialTodo/index.rst
Please review #2532.
Backport for 5.2.x.
=> 【1.0.x】check version for 2017 winter en 1.0.x #2532

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/ArchitectureInDetail/MessagingDetail/JMS.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source_en/ImplementationAtEachLayer/CreateProject.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Security/SecureLoginDemo.rst
Please review #2532.
Backport for 5.2.x.
Translate for 5.2.x.
=> 【5.2.x】check version for 2017 winter en

source/Appendix/EnvironmentIndependency.rst, source/Appendix/ProjectStructureStandard.rst, source/Appendix/TagLibAndELFunctions.rst, source/ArchitectureInDetail/Codelist.rst, source/ArchitectureInDetail/DataAccessCommon.rst, source/ArchitectureInDetail/DataAccessJpa.rst, source/ArchitectureInDetail/FileDownload.rst, source/ArchitectureInDetail/FileUpload.rst, source/ArchitectureInDetail/PropertyManagement.rst, source/ArchitectureInDetail/REST.rst, source/ArchitectureInDetail/Validation.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/DomainLayer.rst, source/Overview/FirstApplication.rst, source/Overview/SpringMVCOverview.rst, source/Security/Authorization.rst, source/TutorialTodo/index.rst
Please review #2532.
Backport for 5.2.x.
=> 【1.0.x】check version for 2017 winter 1.0.x #2532

source_en/Security/Authentication.rst
Please review #1961 ( #2157)
.
=> fix version in the page link #1961

source_en/Security/Authentication.rst
=> fix version in the page links #1961

source_en/Security/Authentication.rst
=> [5.2.x] Add note for SessionAuthenticationStrategy in English version. #1961

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> #2433 Modified description of @URL

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
=> #2429 Changed guideline for typehandler

source_en/ImplementationAtEachLayer/DomainLayer.rst
=> #2432 Modified description of interface and base class

source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst
=> #2462 Added AsyncRestTemplate interceptors

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/Introduction/ChangeLog.rst
=> #2463 Added that TypeHandlers are autodetected since MyBatis3.4

source_en/ImplementationAtEachLayer/ApplicationLayer.rst, source_en/Introduction/ChangeLog.rst, source_en/Security/Authentication.rst
=> #2472 Added description and change logs of view controller for spring4.3

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst, source_en/ArchitectureInDetail/DataAccessDetail/ExclusionControl.rst, source_en/Introduction/ChangeLog.rst
=> #2483 Added warning for nowait issue on postgreSQL

source/Security/OAuth.rst
Please review #2635.
Fixed table's height that didn't fit in one page.
=> fix table height for oauth pdf #2635

source_en/Introduction/ChangeLog.rst, source_en/Security/LinkageWithBrowser.rst
=> #2435 Support for HTTP public key pinning

source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/Introduction/ChangeLog.rst
=> #2461 Added about handling of fatal errors

source_en/Introduction/ChangeLog.rst, source_en/Security/Authorization.rst
=> #2471 Added description for support for path variables

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/Introduction/ChangeLog.rst, source_en/Tutorial/TutorialTodo.rst
=> #2501 Change aggressive loading to false

source_en/ArchitectureInDetail/WebApplicationDetail/Internationalization.rst, source_en/Introduction/ChangeLog.rst
=> #2502 Added desc when internationalization is not applicable

source_en/Introduction/ChangeLog.rst, source_en/Security/Authentication.rst
=> #2516 Improved description of securerandom

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/Introduction/ChangeLog.rst
=> #2517 Added description of validated values

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/ArchitectureInDetail/MessagingDetail/JMS.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst
=> #2522 Support for JBoss 7

source_en/Introduction/ChangeLog.rst, source_en/Overview/FrameworkStack.rst
=> #2535 Updated new OSS stacks

source_en/Introduction/ChangeLog.rst, source_en/Security/Authorization.rst
=> #2536 Added desc for warning for access control for specific URL

source_en/ImplementationAtEachLayer/ApplicationLayer.rst, source_en/Introduction/ChangeLog.rst
=> #2543 Desc corrected for dependency lib version

source_en/Appendix/Nexus.rst, source_en/Introduction/ChangeLog.rst
=> translate about maven central transition #2581

source_en/Security/LinkageWithBrowser.rst
=> Added translation

source/Introduction/ChangeLog.rst
=> Add changes log for 5.1.2 in 2017 winter.#2616

source/Introduction/ChangeLog.rst
=> Add changes log for 5.0.3 in 2017 winter.#2106

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
(cherry picked from commit 1d52e050788cc83da9ad7c23bd51348720b5a805)
Please review #2433.
=> #2433 Modified description of @URL(backport for 5.2.1)

source_en/ArchitectureInDetail/DataAccessDetail/DataAccessCommon.rst, source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ImplementationAtEachLayer/ApplicationLayer.rst, source_en/ImplementationAtEachLayer/CreateProject.rst
=> #2564 Support for Tomcat8.5

source_en/ArchitectureInDetail/WebApplicationDetail/Internationalization.rst, source_en/Introduction/ChangeLog.rst
=> Issues/#2502 backport for 5.2.1.

source_en/ImplementationAtEachLayer/DomainLayer.rst
(cherry picked from commit 8b4180f4d29507fb6195ac85b9eb66b5bb1ad69f)
Please review #2432.(backport for 5.2.1)
=> Modified description of interface and base class #2432 (backport for 5.2.1)

source_en/Security/Authorization.rst
=> translate #2648

source_en/Introduction/ChangeLog.rst, source_en/Security/Authentication.rst
=> Issues/#2516 improve desc of securerandom(backport for 5.2.1.)

README.md
=> [master]Modified "How to contribute" URL in README.md.#2660

README.md
=> [5.3.x]Update README.md (after "2017 winter" release) #2660 

README.md
=> [5.2.x]Update README.md (after "2017 winter" release) #2660 

README.md
=> [5.1.x]Update README.md (after "2017 winter" release) #2660 

README.md
=> [1.0.x]Modified Terms of use URL in README.md.#2660

README.md
=> [5.0.x]Modified Terms of use URL in README.md.#2660

README.md
=> [master]Modified Terms of use URL in README.md.#2660

README.md
=> [5.3.x]Modified Terms of use URL in README.md.#2660

README.md
=> [5.1.x]Modified Terms of use URL in README.md.#2660

README.md
=> [5.2.x]Modified Terms of use URL in README.md.#2660

source_en/Introduction/ChangeLog.rst, source_en/Security/Authorization.rst
=> #2536 backport for 5.2.1

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/Introduction/ChangeLog.rst
=> Issues/#2517 add desc of validated value(backport for 5.2.1.)

source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/Introduction/ChangeLog.rst
=> translate #1704

source_en/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst, source_en/Introduction/ChangeLog.rst
=> translate #1293

source_en/ArchitectureInDetail/WebApplicationDetail/Codelist.rst, source_en/Introduction/ChangeLog.rst
=> Added translation for 1939 target files

source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Introduction/ChangeLog.rst, source_en/Overview/FirstApplication.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialTodo.rst
=> fix almost all previous modification

source_en/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst, source_en/Introduction/ChangeLog.rst
(cherry picked from commit 79fed3ea15fc3c43d6fa2f9b385a645db9160c4f)
backport for 5.2.1
Please review #2641.
=> translate #1293(backport for 5.2.1)

source_en/Introduction/ChangeLog.rst, source_en/Security/Authorization.rst
=> translate #2565

source_en/Introduction/ChangeLog.rst, source_en/Introduction/TermsOfUse.rst
=> translate #2625

source_en/Introduction/ChangeLog.rst
=> Added translation for issue 2599 for 5.2.1

source_en/Appendix/Lombok.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/SystemDate.rst, source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/ArchitectureInDetail/MessagingDetail/JMS.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Security/SpringSecurity.rst, source_en/Tutorial/TutorialTodo.rst
=> Issues/2622 backport for 5.2.1

source_en/ImplementationAtEachLayer/ApplicationLayer.rst
=> remove sentence

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> fix links. refs #2718

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> Issues/2718 backport for 5.1.x

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> Issues/2718 backport for 5.3.x

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> improve password reissue section. #2515

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> [5.3.x] improve password reissue #2515

source/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialSecurity.rst
=> unify the quote style into double quotations in jsp example #2690

source/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialSecurity.rst
(cherry picked from commit fdd458e4619ab309bf3a40e01f07888b3c11f610)
Please review #2690.
=> [5.3.x] unify the quote style into double quotations #2690

source_en/Security/OAuth.rst
=> #2635 Fix table height for OAuth

source_en/Appendix/Lombok.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst
=> #2047 fixed inconsistent expressions

source/Tutorial/TutorialREST.rst, source_en/Tutorial/TutorialREST.rst
=> fixed description item no in spring-mvc-rest.xml(sample code). #2694

source_en/ImplementationAtEachLayer/ApplicationLayer.rst, source_en/Introduction/ChangeLog.rst
=> #2518 added change logs for 2533 correspondence

source/Tutorial/TutorialREST.rst
=> Delete ControllerAdvice annotation attribute. #2281

source_en/Introduction/ChangeLog.rst, source_en/Security/Authentication.rst
=> #785 Added desc about checkbox value

source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/Introduction/ChangeLog.rst
=> #2190 fix note for sending email

source_en/Introduction/ChangeLog.rst
=> #2651_sort_changelog

source_en/Introduction/ChangeLog.rst, source_en/Security/Authentication.rst
=> back port into translation/5.2.1

source_en/ArchitectureInDetail/MessagingDetail/Email.rst, source_en/Introduction/ChangeLog.rst
=> backport into translation/5.2.1

source_en/Introduction/ChangeLog.rst
=> sort changelog 5.2.1 #2651

source/Security/Tutorial.rst, source/TutorialTodo/index.rst
Please review #2360. Backport for 5.1.2
=> [5.1.x] Fix description about database initiarize in Spring security tutorial #2360

source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/ImplementationAtEachLayer/CreateProject.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Overview/FrameworkStack.rst, source/Security/SecureLoginDemo.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ImplementationAtEachLayer/CreateProject.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Overview/FrameworkStack.rst, source_en/Security/SecureLoginDemo.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialTodo.rst
=> 5.2.x typo of modify with Japanese and English  #2695

source/Appendix/CreateProjectFromBlank.rst, source/Overview/FirstApplication.rst, source/Overview/FrameworkStack.rst, source/Security/Tutorial.rst, source/TutorialREST/index.rst, source/TutorialTodo/index.rst, source/index.rst
=> 1.0.x typo of modify #2695

source_en/Tutorial/TutorialTodo.rst
=> 5.2.x typo_of_caret_modify of english version. #2761

source/Appendix/CreateProjectFromBlank.rst, source/Overview/FirstApplication.rst, source/Overview/FrameworkStack.rst, source/Security/Tutorial.rst, source/TutorialREST/index.rst, source/TutorialTodo/index.rst, source/index.rst
(cherry picked from commit 1ee7ca82175d1ab0ec3ca8b84343af8721a1c131)
Please review #2695. Backport for 1.0.6.
=> [1.0.6.RELEASE] Typo of version #2695

source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/ImplementationAtEachLayer/CreateProject.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Overview/FrameworkStack.rst, source/Security/SecureLoginDemo.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst, source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ImplementationAtEachLayer/CreateProject.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Overview/FrameworkStack.rst, source_en/Security/SecureLoginDemo.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialTodo.rst
Please review #2695. Backport for 5.2.1.RELEASE
=> [5.2.1.RELEASE] Typo of version with Japanese and English #2695

source_en/Tutorial/TutorialTodo.rst
(cherry picked from commit 6c601a9040bbb82975c0a317ae4da0f7ba24e813)
Please review #2761. Backport for 5.2.1.
=> [5.2.1.RELEASE] typo_of_caret_modify of english version #2761

source/Introduction/ChangeLog.rst
=> #2763 ChangeLog update

source/Security/Tutorial.rst, source/TutorialTodo/index.rst
Please review #2360. Backport for 5.0.3
=> [5.0.x] Fix description about database initiarize in Spring security tutorial #2360

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source/Introduction/ChangeLog.rst
=> #2775 soap_timeout_setting_change

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source/Introduction/ChangeLog.rst
=> [5.3.x] #2775 soap_timeout_setting_change

source/Security/Tutorial.rst, source/TutorialTodo/index.rst
Please review #2360. Backport for 1.0.7
=> [1.0.x] Fix description about database initiarize in Spring security tutorial #2360

build-html.bat, build-html_en.bat, build-html_for_githubpages.bat
=> removed pause command. #2777

build-html.bat, build-html_en.bat, build-html_for_githubpages.bat
This pull request is backport for 5.3.1
=> [5.3.x] removed pause command. #2777

build-html.bat, build-html_en.bat, build-html_for_githubpages.bat
This pull request is backport for 5.2.2
=> [5.2.x] removed pause command. #2777

build-html.bat, build-html_en.bat, build-html_for_githubpages.bat
This pull request is backport for 5.1.2
=> [5.1.x] removed pause command. #2777

build-html.bat, build-html_en.bat, build-html_for_githubpages.bat
This pull request is backport for 5.0.3
=> [5.0.x] removed pause command. #2777

build-html.bat, build-html_en.bat, build-html_for_githubpages.bat
This pull request is backport for 1.0.7.
=> [1.0.7] removed pause command. #2777

source/ImplementationAtEachLayer/CreateProject.rst, source_en/ImplementationAtEachLayer/CreateProject.rst
=> typo of caret at maven command for master. #2762

source/ArchitectureInDetail/Ajax.rst, source/ArchitectureInDetail/DataAccessMybatis2.rst, source/ArchitectureInDetail/ExceptionHandling.rst, source/ArchitectureInDetail/REST.rst, source/ArchitectureInDetail/TilesLayout.rst
=> 1.0.x guess to fixed language of code-block. #2778

source/ArchitectureInDetail/Ajax.rst, source/ArchitectureInDetail/DataAccessMyBatis3.rst, source/ArchitectureInDetail/ExceptionHandling.rst, source/ArchitectureInDetail/REST.rst, source/ArchitectureInDetail/TilesLayout.rst, source_en/ArchitectureInDetail/Ajax.rst, source_en/ArchitectureInDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/ExceptionHandling.rst, source_en/ArchitectureInDetail/REST.rst, source_en/ArchitectureInDetail/TilesLayout.rst
=> 5.0.x guess to fixed language of code-block. #2778

source/ArchitectureInDetail/Ajax.rst, source/ArchitectureInDetail/DataAccessMyBatis3.rst, source/ArchitectureInDetail/ExceptionHandling.rst, source/ArchitectureInDetail/REST.rst, source/ArchitectureInDetail/TilesLayout.rst, source/Security/SessionManagement.rst, source_en/ArchitectureInDetail/Ajax.rst, source_en/ArchitectureInDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/ExceptionHandling.rst, source_en/ArchitectureInDetail/REST.rst, source_en/ArchitectureInDetail/TilesLayout.rst, source_en/Security/SessionManagement.rst
=> 5.1.x guess to fixed language of code-block. #2778

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source/ArchitectureInDetail/WebApplicationDetail/Ajax.rst, source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/Security/SessionManagement.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Ajax.rst, source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/Security/SessionManagement.rst
=> 5.2.x guess to fixed language of code-block. #2778

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source/ArchitectureInDetail/WebApplicationDetail/Ajax.rst, source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/Security/SessionManagement.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Ajax.rst, source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/Security/SessionManagement.rst
=> 5.3.x guess to fixed language of code-block. #2778

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source/ArchitectureInDetail/WebApplicationDetail/Ajax.rst, source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/Security/SessionManagement.rst, source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Ajax.rst, source_en/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source_en/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source_en/ArchitectureInDetail/WebServiceDetail/REST.rst, source_en/Security/SessionManagement.rst
=> master guess to fixed language of code-block. #2778

source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/Introduction/ChangeLog.rst
=> Fix description about controller return value in Apache Tiles. #2717

source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/Introduction/ChangeLog.rst
Please review #2717. Backport for 5.3.1.
=> [5.3.x] Fix description about controller return value in Apache Tiles #2717

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
=> Minor typos of Exception Name. #2824

source_en/Security/Authorization.rst
=> Typo of version with English. #2645

source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/Introduction/ChangeLog.rst
Please review #2717. Backport for 5.2.2.
=> [5.2.x] Fix description about controller return value in Apache Tiles #2717

source/Security/OAuth.rst
=> improve the chapter structure of oauth. #2818

source_en/Security/Authorization.rst
(cherry picked from commit dd5b96b14771b4c15cba5188b6ad5703d36d2a5d)
Please review #2645.  Backport for 5.3.1
=> [5.3.1]Typo of version with English. #2645

source/Security/SpringSecurity.rst
=> Alter natural expression in SpringSecurity #2437

source/Security/SpringSecurity.rst
(cherry picked form commit 66e54ecd57a57e7964f02fc8fe41991ab90e40de)
Please review #2437. Backport for 5.3.1.
=> [5.3.1]Alter natural expression in SpringSecurity #2437

source/ArchitectureInDetail/TilesLayout.rst, source/Introduction/ChangeLog.rst
Please review #2717. Backport for 5.1.2.
=> [5.1.x] Fix description about controller return value in Apache Tiles #2717

source/ArchitectureInDetail/TilesLayout.rst, source/Introduction/ChangeLog.rst
Please review #2717. Backport for 5.0.3.
=> [5.0.x] Fix description about controller return value in Apache Tiles #2717

source/Introduction/ChangeLog.rst
=> Fix order of change history of Apache Tiles. #2717

source/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source/Introduction/ChangeLog.rst, source/Security/OAuth.rst
add BasicAuthorizationInterceptor example and drop how to creating a ClientHttpRequestInterceptor for basic authentication.
Please review #2742.
=> add BasicAuthorizationInterceptor example #2742

source/ArchitectureInDetail/WebServiceDetail/RestClient.rst, source/Introduction/ChangeLog.rst, source/Security/OAuth.rst
Please review #2742 .
(cherry picked from commit 01dd52af4acdd386c20e575a4783e15319d380a8)
=> [5.3.x] add BasicAuthorizationInterceptor example and drop original implementation #2742

source/ArchitectureInDetail/TilesLayout.rst, source/Introduction/ChangeLog.rst
Please review #2717. Backport for 1.0.7
=> [1.0.x] Fix description about controller return value in Apache Tiles #2717

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/Introduction/ChangeLog.rst
=> Display validation message used custom annotation with compare #2822

source_en/Introduction/ChangeLog.rst
=> The table layout collapse of ChangeLog of English version. #2862

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/Introduction/ChangeLog.rst
Please review #2822.
(cherry picked from commit a0d40026823df571563275c304703c4f8cd9d8b5)
=> [5.3.x]display validation message used custom annotation with compare #2822

source_en/Introduction/ChangeLog.rst
(cherry picked from commit a2f228c3ae7d2491f2ee0a007872bd1e1d8f0106)
Please review #2862 .Backport for 5.3.1.
=> [5.3.1.]The table layout collapse of ChangeLog of English version. #2862

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> Modify implementation example of account lockout. #2734

ISSUE_TEMPLATE.md
=> Update issue template #2798

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
Please review #2734. Backport for 5.3.1
=> [5.3.x] Modify implementation example of account lockout. #2734 

source/Introduction/ChangeLog.rst, source/Security/Authentication.rst
=> Add note for risk that plaintext passwords are described log. #2092

Makefile
=> [1.0.x]Changed Makefile like master branch. #2882

Makefile
Please review #2882.
Backport for 5.0.x.
=> [5.0.x]Changed Makefile like master branch.#2882

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
This pull request is backport for 5.2.2.
=> [5.2.x]Modified description of HandlerExceptionResolverLoggingInterceptor and related description error. #2794

source/ArchitectureInDetail/ExceptionHandling.rst
This pull request is backport for 5.1.2.
=> [5.1.x]Modified description of HandlerExceptionResolverLoggingInterceptor and related description error. #2794

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
This pull request is backport for 5.3.1.
=> [5.3.x] Modified description of HandlerExceptionResolverLoggingInterceptor and related description error. #2794

source/ArchitectureInDetail/ExceptionHandling.rst
Please review #2794.
This pull request is backport for 5.0.3.
=> [5.0.x] Modified description of HandlerExceptionResolverLoggingInterceptor and related description error. #2794

source/ArchitectureInDetail/ExceptionHandling.rst
This pull request is backport for 1.0.7.
=> [1.0.x] Modified description of HandlerExceptionResolverLoggingInterceptor and related description error. #2794

source/Introduction/ChangeLog.rst
=> Added this issue to ChangeLog. #2794

source/Introduction/ChangeLog.rst
This pull request is backport for 5.3.1.
=> [5.3.x]Added this issue to ChangeLog. #2794

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=> Validation - Explanation of group validation is incorrect.  #2792

source_en/Security/index.rst
=> Issues/#2855 backport for 5.1.3 #2855

source/Introduction/ChangeLog.rst
This pull request is backport for 5.2.2.
=> [5.2.x] Added this issue to ChangeLog. #2794

source/Introduction/ChangeLog.rst
This pull request is backport for 5.1.2.
=> [5.1.x] Added this issue to ChangeLog. #2794

source/Introduction/ChangeLog.rst
This pull request is backport for 5.0.3.
=> [5.0.x] Added this issue to ChangeLog. #2794

source/Introduction/ChangeLog.rst
This pull request is backport for 1.0.7.
=> [1.0.x] Added this issue to ChangeLog. #2794

ISSUE_TEMPLATE.md
=> Add 'Final Solution' section to Issue Template #2907

source_en/Introduction/ChangeLog.rst
=> modify chapters composition of chapter9 changelog #2855

source_en/Introduction/ChangeLog.rst
(cherry picked from commit 7b83c3ba8ef03a32e6595f362df058da8a2d9221)
Please review #2855
=> [5.3.x] modify chapters composition of chapter9 add changelog #2855

source/ImplementationAtEachLayer/DomainLayer.rst, source_en/ImplementationAtEachLayer/DomainLayer.rst
Please review #2008.
backport for 5.3.1.
=> [5.3.x]Delete Note Transactional timeout when using MyBatis3.3

source/Introduction/ChangeLog.rst
=> add changelog. #2818

source/Introduction/ChangeLog.rst, source/Security/OAuth.rst
=> [5.3.x]improve the chapter structure of oauth #2818

source/Introduction/ChangeLog.rst
=> Add OAuth changelog #2891

source/Introduction/ChangeLog.rst
=> [5.3.x]Add OAuth changelog #2891

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
=>  Inappropriate code-highlight. #2903  

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
Please review #2903 .
backport for 5.3.x
=> [5.3.x]Inappropriate code-highlight. #2903 

source/Security/SecureLoginDemo.rst, source_en/Security/SecureLoginDemo.rst
=> Improve some code of EncodedPasswordHistoryRule #2966

source/Overview/FirstApplication.rst, source/Security/Authorization.rst, source/Tutorial/TutorialREST.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst
=> Remove definition of trimTokens for Guideline #2941

source/Introduction/ChangeLog.rst
=> Remove definition of trimTokens for Guideline (add ChangeLog) #2941

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source/Introduction/ChangeLog.rst
=> The description of the SOAP server architecture is incorrect #2770

source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source/Overview/FrameworkStack.rst
=> Explanation of how to use the codepoints libraries is not kind #2785

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source/Introduction/ChangeLog.rst
=> [5.3.x]The description of the SOAP server architecture is incorrect #2770

source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Security/Authorization.rst, source/Tutorial/TutorialREST.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst
=> [5.3.x] Remove definition of trimTokens for Guideline #2941

theme/solar/README.rst, theme/solar/layout.html, theme/solar_for_githubpages/README.rst, theme/solar_for_githubpages/layout.html
=> Broken link vkvn of copyright #2901

source/ArchitectureInDetail/DataAccessDetail/ExclusionControl.rst, source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/ImplementationAtEachLayer/CreateProject.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FrameworkStack.rst, source/Security/SecureLoginDemo.rst
=> fix version for release 5.3.1. #3030

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst
=> modified reflect the change of blank projects. #3031

source/Introduction/ChangeLog.rst
=> add changes log for 5.3.1. #3032

source_en/ArchitectureInDetail/DataAccessDetail/ExclusionControl.rst, source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source_en/ImplementationAtEachLayer/CreateProject.rst, source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FrameworkStack.rst, source_en/Security/SecureLoginDemo.rst
=> fix version for release 5.3.1_en. #3030

source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source_en/Overview/FirstApplication.rst, source_en/Tutorial/TutorialSecurity.rst, source_en/Tutorial/TutorialTodo.rst
=> modified reflect the change of blank projects for English Guideline. #3031

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst
=> [5.3.1] fix broken link. #3041

source_en/Introduction/ChangeLog.rst
=> add changes log for 5.3.1_en. #3032

ISSUE_TEMPLATE.md
=> fix 'Fix Version/s' in 5.3.x next release changed to 5.3.2. #3044

source/Introduction/ChangeLog.rst, source_en/Introduction/ChangeLog.rst
=> Modified 5.3.1 to 5.3.2 and add 5.3.1 changeLog. #3051

source/Security/OAuth.rst
Please review #3010 .
PDF化が途中で止まってしまっていたので、`tabularcolumns`を修正しました。
=> Modify tabularcolumns #3010

source/Overview/FrameworkStack.rst
=> add library start infomation. #2937

source/Overview/FrameworkStack.rst
(cherry picked from commit d161dea434271e49fb5786fffa260c4cb44733e7)
Please review #2937.
=> [5.3.x] add library start infomation. #2937

source/Overview/FrameworkStack.rst
(cherry picked from commit d161dea434271e49fb5786fffa260c4cb44733e7)
Please review #2937.
=> [5.2.x] add library start infomation. #2937

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/Security/OAuth.rst
=> modify tip for friendly http error pages. #2912

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/Security/OAuth.rst
Please review #2912 .
(backport 5.3.x)
=> [5.3.x]modify tip for friendly http error pages #2912

source/Introduction/ChangeLog.rst, source/Security/LinkageWithBrowser.rst
Please review #2913.
#3069 でのリベースで別のPRが混じってしまったので、
こちらで再度PRします。
=> add warning cache control response header #2913

source/Introduction/ChangeLog.rst, source/Security/Authentication.rst
Please review #3011 .
ノートにPBKDF2についての記述を追加しました。
BCyptアルゴリズムを推奨する説明を修正しました。
=> Add note about Pbkdf2PasswordEncoder #3011

source/Introduction/ChangeLog.rst, source/Security/Authentication.rst
Please review #3011 
(backport 5.3.x)
=> [5.3.x]Add note about Pbkdf2PasswordEncoder #3011

source/Overview/SpringMVCOverview.rst
Fix Typo SpringMVCOverview[Common] #2995.
=> Fix Typo SpringMVCOverview.rst [Common] #2995

source/Security/Authorization.rst
=> Typo in SpringSecurityAuthorization.  #3055

source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
Fix source code exsample [JSP] #3027
Please review.
=> Fix source code exsample [JSP] #3027

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst
(cherry picked from commit d374de3ea27a9a76c28e60018283c9e28ebe7133)
Please review #3061.
=> [5.3.x] fixed terasoluna-gfw-validator update version [Common] #3061

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
=> modify access policy that uses path path variables. #3090

source/Introduction/ChangeLog.rst, source/Security/Authorization.rst
Please review #3090 .
(backport 5.3.x)
=> [5.3.x]modify access policy that uses path variables. #3090

source/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst
Fix Expression csrf [Common] #3028
Please review.
=> Fix Expression csrf [Common] #3028

source/Security/CSRF.rst
Fix hidden item expression [Common] #3038
Please review.
=> Fix hidden item expression [Common] #3038

source/Overview/SpringMVCOverview.rst
(cherry picked from commit 8392211b9075019b6509aefb3dde5d075ad9c489)
Please review #2995.
=> [5.3.x]Fix Typo SpringMVCOverview.rst[Common] #2995

source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
(cherry picked from commit bc9984ee39f4a8d454a2c11658778ae97850eb45)
Please review #3027.
=> [5.3.x]Fix source code exsample [JSP] #3027

source/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst
(cherry picked from commit ebde68f7565de55195b10b94334a33bd54d5e0a4)
Please review #3028.
=> [5.3.x]Fix Expression csrf [Common] #3028

source/Security/Authorization.rst
@yoshikawaa 
(cherry picked from commit 8b3b6f38f2748da4fb72a648fcaf04a8dea8c900)
Please review #3055.
=> [5.3.x] Typo in SpringSecurityAuthorization.  #3055

source/Security/CSRF.rst
(cherry picked from commit 47ecc508de85b2bb75211c4170732e66fbe5f1e8)
Please review #3038.
=> [5.3.x]Fix hidden item expression [Common] #3038

source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
Fix Expression of Transition [Common] #3026
Please review.
=> Fix Expression of Transition [Common] #3026

source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
(cherry picked from commit 9b04a3f4d1ada4073fe7d8fb10d8f69f3735099b)
Please review #3026.
=> [5.3.x]Fix Expression of Transition [Common] #3026

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
=> fix blank project archetype number #3056

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
(cherry picked from commit dd711b638f1a961b107aeddb087722f527c752c0)
Please review #3056 .
This PR is backport for 5.3.x
=> [5.3.x] fix blank project archetype number #3056

theme/solar/README.rst, theme/solar/layout.html, theme/solar_for_githubpages/README.rst, theme/solar_for_githubpages/layout.html
Please review #2901.
レビュー前に妥当性の確認（こちらはコンフリクト未発生ですが念のため）から、その後の対応まで
@btyanagawamg
に依頼しています。
=> [5.3.x]Broken link vkvn of copyright [Common] #2901

source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/Pagination.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/Authentication.rst, source/Security/OAuth.rst, source/Security/SecureLoginDemo.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialSession.rst, source/Tutorial/TutorialTodo.rst
=> fix blank project change #3106

source/Overview/FrameworkStack.rst
=> fixed jackson-annotations version #3061

source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/Pagination.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/Authentication.rst, source/Security/OAuth.rst, source/Security/SecureLoginDemo.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialSession.rst, source/Tutorial/TutorialTodo.rst
Please review #3106 .
This PR is backport for 5.3.x
=> [5.3.x] fix blank project change #3106

source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
One more Fix Expression of Transition [Common] #3026
Please review.
=> One more Fix Expression of Transition [Common] #3026

source/ArchitectureInDetail/DataAccessDetail/ExclusionControl.rst, source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/ImplementationAtEachLayer/CreateProject.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Overview/FrameworkStack.rst, source/Security/SecureLoginDemo.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialTodo.rst
=> update terasoluna version to 5.3.2 #3061

source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
(cherry picked from commit f6f97dd308582e62a96637a24fe54e6d28dc64ac)
Please review #3026.
=> [5.3.x]One more Fix Expression of Transition [Common] #3026

source/Introduction/ChangeLog.rst
=> add changelog about testguide #1817

source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source/Security/Authentication.rst, source/Security/LinkageWithBrowser.rst
=> fixed broken link #3041

source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/ArchitectureInDetail/WebServiceDetail/SOAP.rst, source/Security/Authentication.rst, source/Security/LinkageWithBrowser.rst
=> [5.3.x] fix broken link 

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
=> fix oracle id and postgres version for blank project #3130

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
(cherry picked from commit fa04a804e560a2f9fc487527905bcef214efa0a3)
Please review #3130 .
This PR is backport for 5.3.x
=> [5.3.x] fix oracle id and postgres version for blank project #3130

source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/Tutorial/TutorialTodo.rst
=> warnings occurred while building pdf and html #3120

source/ArchitectureInDetail/WebServiceDetail/REST.rst, source/Tutorial/TutorialTodo.rst
Please review #3120 .
(backport to 5.3.x)
=> [5.3.x]warnings occurred while building pdf and html #3120

source/Introduction/ChangeLog.rst
=> modified ChangeLog #3126

source/Introduction/ChangeLog.rst
=> added Migration Guide #3126

source/Introduction/ChangeLog.rst
=> [5.3.x] modified ChangeLog #3126

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
(cherry picked from commit fa04a804e560a2f9fc487527905bcef214efa0a3)
Please review #3130
=> [5.2.x] fix oracle id and postgres version for blank project #3130

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
(cherry picked from commit fa04a804e560a2f9fc487527905bcef214efa0a3)
Please review #3130
=> [5.1.x] fix oracle id and postgres version for blank project #3130

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
(cherry picked from commit fa04a804e560a2f9fc487527905bcef214efa0a3)
Please review #3130 .
=> [5.0.x] fix oracle id and postgres version for blank project #3130

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
(cherry picked from commit dd711b638f1a961b107aeddb087722f527c752c0)
Please review #3056 .
=> [5.2.x] fix blank project archetype number #3056

source/Appendix/CreateProjectFromBlank.rst
=> [5.1.x] fix blank project archetype number #3056

source/Appendix/CreateProjectFromBlank.rst
=> [5.0.x] fix blank project archetype number #3056

theme/solar/README.rst, theme/solar/layout.html, theme/solar_for_githubpages/README.rst, theme/solar_for_githubpages/layout.html
=> [5.2.x] Broken link vkvn of copyright [Common] #2901

theme/solar/README.rst, theme/solar/layout.html, theme/solar_for_githubpages/README.rst, theme/solar_for_githubpages/layout.html
=> [5.1.x] Broken link vkvn of copyright [Common] #2901

theme/solar/README.rst, theme/solar/layout.html, theme/solar_for_githubpages/README.rst, theme/solar_for_githubpages/layout.html
=> [5.0.x] Broken link vkvn of copyright [Common] #2901

theme/solar/README.rst, theme/solar/layout.html, theme/solar_for_githubpages/README.rst, theme/solar_for_githubpages/layout.html
(cherry picked from commit 50467585a2a27c64fc2e3c80ae12231c400fad8b)
Please review #2901 .
=> [1.0.x] Broken link vkvn of copyright [Common] #2901

source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst, source/ArchitectureInDetail/WebApplicationDetail/Pagination.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/Authentication.rst, source/Security/SecureLoginDemo.rst, source/Tutorial/TutorialSecurity.rst, source/Tutorial/TutorialSession.rst, source/Tutorial/TutorialTodo.rst
=> [5.2.x] reflect format change of blank project #3106

source/ArchitectureInDetail/MessageManagement.rst, source/ArchitectureInDetail/Pagination.rst, source/ArchitectureInDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/Authentication.rst, source/Security/SecureLoginDemo.rst, source/Security/Tutorial.rst, source/TutorialSession/index.rst, source/TutorialTodo/index.rst
=> [5.1.x] reflect format change of blank project #3106

source/ArchitectureInDetail/MessageManagement.rst, source/ArchitectureInDetail/Pagination.rst, source/ArchitectureInDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/ImplementationAtEachLayer/CreateWebApplicationProject.rst, source/Overview/FirstApplication.rst, source/Security/Tutorial.rst, source/TutorialTodo/index.rst
=> [5.0.x] reflect format change of blank project #3106

source/ArchitectureInDetail/MessageManagement.rst, source/ArchitectureInDetail/Pagination.rst, source/ArchitectureInDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/Overview/FirstApplication.rst, source/Security/Authentication.rst
=> [1.0.x] reflect format change of blank project #3106

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst, source/Security/SecureLoginDemo.rst
=> Modifier 'public' Should Be Removed From Inner Annotation In Custom Bean Validation Template  #2999

source/Security/OAuth.rst
=> modified oauthConfirm.jsp code example(label tag) #3178

source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst
=> delete extra space(file upload) #3192

source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst
=> Improve model name(file upload) #3190

source/Security/OAuth.rst
(cherry picked from commit 2d68a311b479cabd10a47267a9a31c8f394b85bd)
Please review #3178
=> [5.4.x] modified oauthConfirm.jsp code example(label tag) #3178

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/Introduction/CriteriaBasedMapping.rst
=> modified reference label(exceptioncode) #3202

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst, source/Introduction/CriteriaBasedMapping.rst
(cherry picked from commit 1d5c51efe635368f9ce48c86b061c2d4ae028d89)
Please review #3202.
=> [5.4.x]modified reference label(exceptioncode) #3202

source/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst
(cherry picked from commit 80aaa4ddf9bb20cf73ed2d8f9a371a1f6f59c66b)
Please review #3204 .
=> [5.4.x]modified multiple file upload view #3204

source/ArchitectureInDetail/WebApplicationDetail/Internationalization.rst
=> modified refelence label in internationalization #3211

source/ArchitectureInDetail/WebApplicationDetail/HealthCheck.rst
(cherry picked from commit 4cbd0271bacee7de0a48dc00e28684a66aa38e59)
Please review #3198.
=> [5.4.x] modified reference label #3198

source/ArchitectureInDetail/WebApplicationDetail/HealthCheck.rst
=> modified reference label #3198

source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst, source/Introduction/ChangeLog.rst
=> codelist bean define to xml instead of @Component #3181

source/ArchitectureInDetail/WebApplicationDetail/HealthCheck.rst
=> modified exclusion settings of authorization in HealthCheck #3221

source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst, source/Introduction/ChangeLog.rst
=> codelist bean define to xml instead of @Component backport to 5.4.x #3181 

source/ArchitectureInDetail/WebApplicationDetail/HealthCheck.rst
(cherry picked from commit c932f0e6eaa42b46d5833c5671913eba16fd610c)
Please review #3221.
=> [5.4.x] modified exclusion settings of authorization in HealthCheck #3221

source/ArchitectureInDetail/WebApplicationDetail/Internationalization.rst
(cherry picked from commit ce8c341b814abc5f12ac3ca3719c98d4d5a2d872)
Please review #3211.
=> [5.4.x] modified refelence label in internationalization #3211

source/Security/OAuth.rst
=>  modified input tag of code block(attributes) #3186

source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst
=> Fixed Typo in Codelist.rst

source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst
=> Modifi CodeListInterceptor Description #3237

source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst
(cherry picked from commit 386663cd7fecbb8af277eb21e3a7e96bad63d265)
Please review #3237.
=> [5.4.x] Modifi CodeListInterceptor Description #3237

source/Tutorial/TutorialSecurity.rst
=> Fix from code-block:: xml to code-block:: jsp in TutorialSecurity #3248

source/Tutorial/TutorialSecurity.rst
(cherry picked from commit 70ed75129ce083cf3ba107b6424cf99569d70f25)
Please review #3248
=> [5.4.x] Fix from code-block:: xml to code-block:: jsp in TutorialSecurity #3248

source/Tutorial/TutorialSecurity.rst
=> Different contents of spring-mvc.xml in TutorialSecurity.rst #3275

source/Tutorial/TutorialSecurity.rst
=> [5.4.x] Different contents of spring-mvc.xml in TutorialSecurity.rst #3275

source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst
=> The TOC in TagLibAndELFunctions.rst has disappeared. #3172

source/Tutorial/TutorialSecurity.rst
Modifi description of "add logout button" image in TutorialSecurity.rst
Please review #3256
=> Modifi description of "add logout button" image in TutorialSecurity.rst #3256

source/Tutorial/TutorialREST.rst, source/Tutorial/TutorialTodo.rst
=> change TodoServiceImpl#findOne method private to public at REST tutorial #3303

source/Tutorial/TutorialSecurity.rst
=> [5.4.x] modifi description of add logout button image in tutorial security.rst 5.4.x #3256

source/Introduction/ChangeLog.rst, source/Tutorial/TutorialSession.rst
=> [5.5.x]Session Tutorial Application is not implemented for tiles #3270 

source/Security/OAuth.rst
=> [5.4.x]modified input tag of code block(attributes) #3186

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Tutorial/TutorialTodo.rst
=> Delete defines View Resolver with bean element #3197

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst, source/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst, source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst, source/ImplementationAtEachLayer/ApplicationLayer.rst, source/Introduction/ChangeLog.rst, source/Overview/FirstApplication.rst, source/Tutorial/TutorialTodo.rst
=> [5.4.x]Delete defines View Resolver with bean element #3197

source/Introduction/ChangeLog.rst
=> [5.4.x] fix change log about codelist bean definision #3329

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> update copylight 2017 to 2018. #3348

conf/html/conf.py, conf/html_for_githubpages/conf.py, conf/latexpdfen/conf.py, conf/latexpdfja/conf.py
=> [5.4.1] update copylight 2017 to 2018. #3348

source/Tutorial/TutorialTodo.rst
Please review #3233 .
#3233 Correspondence omission (There was a place not using the link) was fixed .
=> correct to use link #3233
