terasolunaorg/guideline

source/ArchitectureInDetail/SystemDate.rst
source_en/ArchitectureInDetail/SystemDate.rst

Improved description in SystemDate.rst(applied review comments). #22

---

source/ArchitectureInDetail/Codelist.rst
source_en/ArchitectureInDetail/Codelist.rst

Improved description in Codelist.rst(applied review comments). #19

---

source_en/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/Utilities/JodaTime.rst

Translated from #577 .
Please review #553 .

Replace DateMidnight with LocalDate,withTimeAtStartOfDay() in en. #553

---

source/ArchitectureInDetail/Validation.rst
source_en/ArchitectureInDetail/Validation.rst

Improved description in Validation.rst(applied review comments). #14

---

source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

Update Spring version to 3.2.13 #547

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

Improved description in Logging.rst(applied review comments). #15

---

source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

In this PR, modified only FrameworkStack.rst.
Please review #701 .

Added the description of terasoluna-gfw-jodatime in FrameworkStack.rst. #701

---

source/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/REST.rst

Modified javadoc links of Jackson.(2.3->2.4) #503

---

source/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst

Removed the unnecessary description for escaping of wildcard search in DataAccessCommon.rst. #713

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

Updated copyright years to 2013-2015. #719

---

source_en/ImplementationAtEachLayer/DomainLayer.rst

Translated en from #583 .
Please review #562 .

Added the tip about @Transactional of JTA in en. #562

---

source/ArchitectureInDetail/DataAccessCommon.rst

Applied terasolunaorg/terasoluna-gfw#78 in DataAccessCommon.rst.
Please review #712 .

Modified the description about wildcard characters of like-searching. #712

---

source/ArchitectureInDetail/DataAccessCommon.rst

Applied terasolunaorg/terasoluna-gfw#78 in DataAccessCommon.rst.
Backported to 1.0.x from #716 .
Please review #712 .

[1.0.x] Modified the description about wildcard characters of like-searching. #712

---

source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Codelist.rst
source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/FileDownload.rst
source/ArchitectureInDetail/FileUpload.rst
source/ArchitectureInDetail/PropertyManagement.rst
source/ArchitectureInDetail/REST.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Overview/SpringMVCOverview.rst
source/Security/Authorization.rst
source/TutorialTodo/index.rst
source_en/ArchitectureInDetail/Codelist.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/FileDownload.rst
source_en/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/PropertyManagement.rst
source_en/ArchitectureInDetail/Validation.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst
source_en/Overview/FirstApplication.rst
source_en/Overview/FrameworkStack.rst
source_en/Overview/SpringMVCOverview.rst
source_en/Security/Authorization.rst
source_en/TutorialTodo/index.rst

Applied the Spring IO Platform 1.1.1.RELEASE. #482

---

source/ArchitectureInDetail/Ajax.rst
source_en/ArchitectureInDetail/Ajax.rst

masterにも修正漏れがあったので対応しました。
1.0.xmへは、cherry-pick + 個別修正で対応します。
確認お願いします。 #680

Modified meta tag's name for CSRF in Ajax.rst. #680

---

source/ArchitectureInDetail/ExclusionControl.rst
source_en/ArchitectureInDetail/ExclusionControl.rst

Modified wrong sample code in ExclusionControl.rst. #450

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst

主な修正内容は、
* `maven archetype:generate` をバッチモード(-B)に修正
* MyBatis3のカスタマイズが不要だったので削除
* 各ソースの頭にファイル名やタイトルを記載するように修正（可読性の改善）
* noteの位置の移動
です。 #731

Updated the content for 5.0.0 in CreateWebApplicationProject.rst. #731

---

source/TutorialTodo/index.rst

masterはMyBatis2の記載を削除したので、1.0.xのみ対応しました。
確認お願いします。 #545

Fixed the typo in TutorialTodo.rst. #545

---

source/ArchitectureInDetail/ExclusionControl.rst
source_en/ArchitectureInDetail/ExclusionControl.rst

cherry-picked from #738 .
Please review #450 .

[1.0.x] Modified wrong sample code in ExclusionControl.rst. #450

---

source_en/Overview/ApplicationLayering.rst

Modified the translation mistakes in ApplicationLayering.rst. #364

---

source/Appendix/Lombok.rst

Added the description for avoid the circular reference in Lombok.rst. #691

---

source_en/Overview/ApplicationLayering.rst

(cherry picked from commit bc9dc171069be82b22a9f050f8c74cbb4a3e775f)
Please review #364 .

[1.0.x] Modified the translation mistakes in ApplicationLayering.rst. #364

---

source/ArchitectureInDetail/Ajax.rst
source/ArchitectureInDetail/REST.rst

Added the description for avoid the circular reference in REST.rst and Ajax.rst. #691

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

Modified the description mistakes in Authentication.rst. #752

---

source/Security/Authentication.rst

Improved the description of form-login in Authentication.rst. #754

---

source/Security/Authentication.rst

Improved the description of appendix in Authentication.rst. #754

---

source/Security/Authentication.rst

Improved the description of session-management in Authentication.rst. #754

---

source/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/REST.rst

Fixes the typos in REST.rst. #756

---

source_en/ImplementationAtEachLayer/index.rst

#734 
Added "Create web application project" in Index.rst

#734 Updated the index file for Create Web application project

---

source/Security/Authentication.rst

(cherry picked from commit 9fe89bcba25a24f1a118396e08f79df29971beee)
Note : Reverted the english version by manually.
Please review #752 .

[1.0.x] Modified the description mistakes in Authentication.rst. #752

---

source/Security/Authentication.rst

(cherry picked from commit 196c0116020f890d170c3da4cbd135a7aae40cf5)
Note : Conflicts resolved by manually.
Please review #754 .

[1.0.x] Improved the description of session-management in Authentication.rst. #754

---

source/Security/Authentication.rst

(cherry picked from commit ea7f80174a073800edd82f23a1d81f92c08799e8)
Please review #754 .

[1.0.x] Improved the description of form-login in Authentication.rst. #754

---

source/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/REST.rst

(cherry picked from commit 559eb96f9829c78e037aa432477f101f9bad55a9)
Note : Conflicts resolved by manually.
Please review #756 .

[1.0.x] Fixes the typos in REST.rst. #756

---

source/Security/Authentication.rst

(cherry picked from commit 68907dd89e1b3eafe00856859a2437198cb42545)
Please review #754 .

[1.0.x] Improved the description of appendix in Authentication.rst. #754

---

source/Security/Authentication.rst

題材は変更していませんが、`AuthenticationProvider` の拡張のセクションの記載を全体的に見直しました。
加えて、今回のbug fixとして `SessionAuthenticationStrategy` の説明を追加しました。
Please review #765 .

Modified the wrong description of how to extend AuthenticationProvider. #765

---

source/Security/Authentication.rst

Polished the sample code in Authentication. #765

---

source/Security/Authentication.rst

[Changed the configurations for 1.0.x](cc65b3040e807af306d3da2608628a4149b64bed) after cherry-picked from master changes(c32d626a1293e78d1ed43168a7bf240325d49502 and 55498c36e12b6590aaeeae18d816a0f35fb647a0).

[1.0.x] Modified the wrong description of how to extend AuthenticationProvider. #765

---

source/ArchitectureInDetail/Validation.rst

Added the note(warning) of ValidationMessages.properties in Validation.rst #766

---

source/ArchitectureInDetail/Codelist.rst

Added the note of ValidationMessages.properties in Codelist.rst #766

---

source/ArchitectureInDetail/Codelist.rst

(cherry picked from commit cb918b247a1605d8dcd1dfe23791ae563e34e12a)
Note : Conflicts resolved by manually.
Please review #766 .

[1.0.x] Added the note of ValidationMessages.properties in Codelist.rst #766

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

see https://github.com/terasolunaorg/guideline/issues/134#issuecomment-71189986.
Please review #134 .

Update sample code to use @AuthenticationPrincipal. #134

---

source/ArchitectureInDetail/Validation.rst

(cherry picked from commit a07d589032e90923b817b4e810860da9a326fddf)
Please review #766 .

[1.0.x] Added the note(warning) of ValidationMessages.properties in Validation.rst #766

---

source/TutorialREST/index.rst

(cherry picked from commit af0d638e3f0499042b2260dc31778941aecf8704)
Note : Conflicts resolved by manually.
Please review #766 .

[1.0.x] Modified the description of ValidationMessages.properties in TutorilREST/index.rst #766

---

source/Security/Authentication.rst

see https://github.com/terasolunaorg/guideline/issues/134#issuecomment-71189986.
Please review #134 .

Update description of Concurrent Session Control for Spring Security 3.2. #134

---

source/Security/Authentication.rst

see https://github.com/terasolunaorg/guideline/issues/134#issuecomment-71189986.
Please review #134 .

Update description of session-fixation-protection attribute for Spring Security 3.2. #134

---

source/Security/Authentication.rst
source/Security/CSRF.rst

see https://github.com/terasolunaorg/guideline/issues/134#issuecomment-71189986.
Please review #134 .

Update description of session timeout for Spring Security 3.2. #134

---

source/index.rst
source_en/index.rst

Update note of top page. #800

---

source/ArchitectureInDetail/REST.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst

Modified the description of @ControllerAdvice's attributes. #549

---

source/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/REST.rst

Update description of CSRF measures for Spring Security 3.2 in REST.rst. #134

---

source/ArchitectureInDetail/FileUpload.rst
source/Security/CSRF.rst

Apply CommonsUpload. #778

---

source/ArchitectureInDetail/FileUpload.rst
source/Security/CSRF.rst

cherry-pick & modify some description for 1.0.x.
Please review #778 .

[1.0.x] Apply CommonsUpload. #778

---

source/ArchitectureInDetail/FileUpload.rst

Sorry... modify typo(broken link).
Please review #778 .

[1.0.x] Modify broken link. #778

---

source/Introduction/ChangeLog.rst

Add change log for 1.0.2. #804

---

source/ArchitectureInDetail/DataAccessMybatis2.rst

Backport to 1.0.x.
Please review #402 .

[1.0.x] Modify description of NariveJdbcExtractor #402

---

source/Introduction/ChangeLog.rst

Sorry... there was  leakage of addition into change logs.
Please review again. #804

Add change log of TagLibAndELFunctions for 1.0.2. #804

---

source_en/Appendix/TagLibAndELFunctions.rst
source_en/Appendix/index.rst
source_en/Introduction/ChangeLog.rst
source_en/TutorialREST/index.rst

#804: Add change logs for 1.0.2 into English version

---

source_en/Overview/ApplicationLayering.rst

#830 
Chapter 2.4 Application Layering has been confirmed and modified.
Please review it.

Issue #830 Chapter 2.4 Application Layering Confirmation

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

Modify description of include.jsp. #319

---

source/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/FileUpload.rst

Modify wrong explanation of CVE-2014-0050. #846

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

(cherry picked from commit d352bfcb2d88767b4143f572aa3f1163c3130028)
Backport to 1.0.x.
Please review #319 .

[1.0.x] Modify description of include.jsp. #319

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Sorry.. description about return value of batch mode was wrong.
I fixed wrong description.
Please review #46 .

Fixes wrong description about return value of batch mode. #46

---

source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/ExceptionHandling.rst
source/ArchitectureInDetail/ExclusionControl.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/ExclusionControl.rst

* Remove the TODO of PessimisticLockingFailureException
* Update description about exception handling class for the JPA
Please review #556 .

Update about JPA. #556

---

source/Introduction/ChangeLog.rst

Add change logs for 5.0.0. #805

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

* Append the change log of CVE-2014-0050 into FileUpload.rst.
* Append the change log of Authorization.rst into added translation documents.
Please review #804 .

Append change logs for 1.0.2. #804

---

source/ArchitectureInDetail/DataAccessCommon.rst
source/ImplementationAtEachLayer/InfrastructureLayer.rst
source/Overview/ApplicationLayering.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/Pagination.rst
source_en/ArchitectureInDetail/index.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst
source_en/Introduction/CriteriaBasedMapping.rst
source_en/Overview/ApplicationLayering.rst
source_en/Overview/FrameworkStack.rst

Please review #837.
Note:
* Modify Japanese version at some location(corresponding leakage)

Change explanation order of data access. #837

---

source/Introduction/ChangeLog.rst

Sorry..  the link to Spring JIRA issue is wrong.
Please review #805 .

Fix link to Spring JIRA issue. #805

---

source_en/TutorialTodo/index.rst

Fixed the translation mistake under below topic 
3.5.3.3. Create TodoRepositoryImpl
#782

#782 Fixed the translation mistake

---

source_en/Appendix/index.rst

#619 Added Lombok page in to below index file.
source_en\Appendix\index.rst
Also pull requested to merge into master. Please check it is correct or not? 
Please review

#619 Need to add Lombok page into index

---

source/Introduction/ChangeLog.rst

Append change log of DomainLayer.rst for 5.0.0. #805

---

source/Introduction/ChangeLog.rst

* Note of readOnly flag in DomainLayer.rst
Please review #805 .

Append change log for 5.0.0. #805

---

source/ArchitectureInDetail/REST.rst
source/Introduction/ChangeLog.rst
source/TutorialREST/index.rst
source_en/ArchitectureInDetail/REST.rst

[5.0.0] Issues/918 rest wrong exception handling 5.0.0

---

source/ArchitectureInDetail/REST.rst
source/Introduction/ChangeLog.rst
source/TutorialREST/index.rst
source_en/ArchitectureInDetail/REST.rst

[5.0.x] Issues/918 rest wrong exception handling

---

source/Appendix/Nexus.rst

(cherry picked from commit f18c2edef0947ef28f6a84c795978fb4a57bbcbf)
Backported from master branch.
Please review #923(#922) .

[1.0.x] fix typos in Nexus

---

CONTRIBUTING.md

#228: Add the CONTRIBUTING.md

---

source/index.rst
source_en/index.rst

#931: Improve link url for creating a new issue

---

README.md

#926: Add the README.md

---

README.md

backported from master.
Please review #926 .

[5.0.x] #926: Add the README.md

---

README.md

backported from master and minor changes applied.
Please review #926 .

[1.0.x] #926: Add the README.md

---

source/index.rst
source_en/index.rst

(cherry picked from commit 849e4e82702147dcaa2a9611cce549db64c1cc80)
Please review #931 .

[5.0.0] #931: Improve link url for creating a new issue

---

source/index.rst
source_en/index.rst

(cherry picked from commit 849e4e82702147dcaa2a9611cce549db64c1cc80)
Please review #931 .

[1.0.2] #931: Improve link url for creating a new issue

---

source/ArchitectureInDetail/DataAccessJpa.rst

#941
「5.3. データベースアクセス（JPA編）」内にて確認された8件の誤記について、修正対応しました。

Typo DatabaseAccess JPA. #941

---

source/ArchitectureInDetail/DataAccessJpa.rst

#941
(cherry picked from commit 39a20418ab1f77f853235ef7a5ac7d2355c1a43f)

[5.0.x] Typo DatabaseAccess JPA. #941

---

source_en/ArchitectureInDetail/DataAccessJpa.rst

#941: Modify typo in DataAccessJpa.rst

---

source/ArchitectureInDetail/Validation.rst

#952
「5.5. 入力チェック」内にて確認された1件の誤記について、修正対応しました。

Typo Validation. #952

---

source/ArchitectureInDetail/Logging.rst

#955
「5.6. ロギング」内にて確認された3件の誤記について、修正対応しました。

Typo Logging. #955

---

source_en/ArchitectureInDetail/Logging.rst

Typo Logging_en. #955

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

#955
(cherry picked from commit da217b52e42601119589380ed2a3c72054454bf3)
(cherry picked from commit ae6098182e2116395abfc9d990fc9bc281cce0b8)

[5.0.x] Typo Logging #955

---

source/ArchitectureInDetail/ExceptionHandling.rst

#961
「5.7. 例外ハンドリング」内にて確認された誤記について、修正対応しました。

Typo ExceptionHandling. #961

---

source/ArchitectureInDetail/ExceptionHandling.rst

#961
(cherry picked from commit 9da989fcf4983dfd29bb514cff7aae2b6c44475f)

[5.0.x] Typo ExceptionHandling. #961

---

source_en/ArchitectureInDetail/ExceptionHandling.rst

348 Translated Tip of Internet Explorer

---

source_en/ArchitectureInDetail/ExceptionHandling.rst

Please review Cherry-pick to master for issue #348

#348: Translated Tip of Internet Explorer

---

source_en/Security/Authentication.rst

#770 Translated Improved Appendix Description

---

source_en/ArchitectureInDetail/REST.rst

Please review #918 
Rest wrong exception handling to the translation/5.0.0

#918 Rest wrong exception handling

---

source_en/Security/Authentication.rst

#769 Improved Form Login Description

---

source_en/Security/Authentication.rst

#768: Improved Logout Description

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

#903: Modify note about batch execution timing in MyBatis3.rst

---

source_en/Security/Authentication.rst

#786 Translated Auth Provider Description

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

(cherry picked from commit f410f1efd4a6872fe442f4c7b6792d5e773c8ac1)
I backported to 5.0.x.
Please review #903 .

[5.0.x] #903: Modify note about batch execution timing in MyBatis3.rst

---

source_en/ArchitectureInDetail/Codelist.rst
source_en/ArchitectureInDetail/Validation.rst
source_en/TutorialREST/index.rst

#796 Translated Validation Message Prop Description

---

source_en/ArchitectureInDetail/Pagination.rst
source_en/ArchitectureInDetail/REST.rst

Translated API Spec Change Note #883

---

source_en/Security/CSRF.rst

#884 Translated tip of CSRF Request Data Value Processor

---

source_en/ArchitectureInDetail/Pagination.rst
source_en/ArchitectureInDetail/REST.rst

#883
This is Cherry-pick to master 
Please review.

Translated API Spec Change Note

---

source_en/ArchitectureInDetail/DataAccessCommon.rst

#814_Translated modified wild card char descp

---

source/ImplementationAtEachLayer/DomainLayer.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst

#1027: Remove description about the Oracle OC4J in DomainLayer

---

source/ImplementationAtEachLayer/DomainLayer.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst

(cherry picked from commit 9f67d94429dd65d9f23bd896464fbcc4bbd42ef1)
Please review #1027 .

[5.0.x] #1027: Remove description about the Oracle OC4J in DomainLayer

---

source/Overview/FirstApplication.rst

#1004: Fixes a typo in FirstApplication.rst

---

source/Security/Authentication.rst

#1020: fix typo in Security Authentication

---

source/Security/Tutorial.rst

SecurityのTutorial.rstの"てにをは"の誤りを修正。また、不足項目を追記。 #1018

Fix Tutorial.rst of Security #1018

---

source/Overview/ApplicationLayering.rst

#1009: Fixes typos in ApplicationLayering.rst

---

source/TutorialTodo/index.rst
source_en/TutorialTodo/index.rst

TutorialTodoのindex.rstを修正しました。 #1013

Fix index of TutorialTodo #1013

---

source/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/ExceptionHandling.rst

fixed typo in ExceptionHandling.rst #issues/1026

---

source/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/ExceptionHandling.rst

5.0.xへのバックポートです。ご確認をお願いします。#1026

Issues/1026 fix typo in exception handling.rst

---

source/Security/Authorization.rst
source_en/Security/Authorization.rst

typoの修正を行いました。ご確認をお願いします。#1041

fixed typo in Authorization.rst #1041

---

source_en/ArchitectureInDetail/Validation.rst

#885_Translated updated descp of Bean Validation

---

source_en/ArchitectureInDetail/Pagination.rst

#881_Translated modified page link desp

---

source/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/FileUpload.rst

Modified context path #1056

---

source/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/FileUpload.rst

#1058. Corrected Annotation Name.
Please Review

FileUpload Wrong Custom Annotation Fixed #1058

---

source_en/ArchitectureInDetail/Codelist.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst

Fixed the rest file formatting issue #1065 
Please review.

Fixed the rest file formatting issue #1065

---

source_en/ArchitectureInDetail/FileDownload.rst
source_en/ArchitectureInDetail/TilesLayout.rst

Please review #879 
Files committed: 
source/ArchitectureInDetail/FileDownload.rst
source/ArchitectureInDetail/TilesLayout.rst
Notes: 
Pull request for source/ArchitectureInDetail/ExceptionHandling.rst and source/ImplementationAtEachLayer/ApplicationLayer.rst is raised under
https://github.com/terasolunaorg/guideline/issues/580
Pull request for source/Overview/FirstApplication.rst is raised under
https://github.com/terasolunaorg/guideline/issues/831
Pull request for source/TutorialTodo/index.rst is raised under 
https://github.com/terasolunaorg/guideline/issues/782

#879 Translated descp related to mvc view resolver

---

source_en/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/REST.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

Please review #580
Files pushed:
source/ArchitectureInDetail/ExceptionHandling.rst
source/ArchitectureInDetail/REST.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
Notes: 
Pull request for source/ArchitectureInDetail/Validation.rst is raised under
https://github.com/terasolunaorg/guideline/issues/885
Pull request for source/TutorialREST/index.rst is raised under
https://github.com/terasolunaorg/guideline/issues/889

#580 Translated changes related to @ControllerAdviceAttribute

---

source/Appendix/EnvironmentIndependency.rst

Add VirutalWebappLoader alternative for Tomcat 8. #1081

---

source/ArchitectureInDetail/Utilities/Dozer.rst
source_en/ArchitectureInDetail/Utilities/Dozer.rst

fix guideline. #1074

---

source/Appendix/EnvironmentIndependency.rst

(cherry picked from commit cfa882f78a2ba2e801c133f4ad13f2eb50d690ba)

Modify EnvironmentIndependency.rst. #1081

---

source/ArchitectureInDetail/Validation.rst
source_en/ArchitectureInDetail/Validation.rst

fix guideline. #1075

---

source/ArchitectureInDetail/SessionManagement.rst

Modify SessionManagement.rst for session scope. #1082

---

source_en/Introduction/ChangeLog.rst

#893_Translated updated change log

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Fixed typo in DataAccessMyBatis3. #1091

---

source/TutorialREST/index.rst
source_en/TutorialREST/index.rst

Fix PUT Todo in TutorialREST. #1102

---

source_en/Security/Authentication.rst

#767_Translated updated session mgmt description

---

source_en/Security/CSRF.rst

Please review #798 
File committed: 
source/Security/CSRF.rst
Notes: 
source/Security/Authentication.rst is already committed under issue #767

#798 Translated modified CSRF description

---

source_en/ArchitectureInDetail/FileUpload.rst

Please review #809 
File committed: 
source/ArchitectureInDetail/FileUpload.rst
Notes: 
source/Security/CSRF.rst is already committed under issue #798

#809 File Upload Support Commons

---

source_en/Security/SpringSecurity.rst

Please review #886
File committed: 
source/Security/SpringSecurity.rst
Notes: 
source/Overview/FrameworkStack.rst is already committed under issue #829 
source/ImplementationAtEachLayer/DomainLayer.rst is already committed under issue #890

#886 Translated updated Spring FW description

---

source_en/Security/Tutorial.rst

Fixing the Sphinx build fail of #888
Please review.

Fixing Sphinx build fail of #888

---

source_en/ArchitectureInDetail/REST.rst

Fixing Sphinx build fail of #580 
Please review.

Fixing Sphinx build fail of #580

---

source_en/Security/Tutorial.rst

(cherry picked from commit 79980f09215b5cce4450ec97998333cec67bca30)
Cherry-pick to master
Please review Fixing Sphinx build fail of #888

Fixing Sphinex build fail of #888

---

source/ArchitectureInDetail/Codelist.rst

Please review. #1109 
#1115　のコメントを受けて修正しなおしました。

Added description of displaying code label to Codelist.rst. #1109

---

source/Appendix/EnvironmentIndependency.rst

Please review #1081.
I do refactor descriptions of how to deploy to the Tomcat.
* separate the Tomcat 7 and Tomcat 8 descriptions
* add links to configs directory of `terasoluna-tourreservation-env`

#1081: Improve descriptions of how to deploy to the Tomcat

---

source_en/ArchitectureInDetail/SessionManagement.rst

I translate to English.
Please review #1082 .

#1082: Modify explanations of how to create a session-scoped bean. (English translation)

---

source/ArchitectureInDetail/SessionManagement.rst

I reflect a modification leakage.
Please review #1082 .

#1082: Add a proxyMode attribute in sample code of Appendix

---

source_en/ArchitectureInDetail/SessionManagement.rst

(cherry picked from commit 48765a206da7f340bf4c63a018b02cf1f5a508b2)
I backport to 5.0.x.
Please review #1082 .

[5.0.x] #1082: Modify explanations of how to create a session-scoped bean. (English translation)

---

source/ArchitectureInDetail/Codelist.rst

* Improve indent of code-block and list-table
* Add inner link
I improve above.
Please review #1109 .

#1109: Improve explanation of how to display a code name

---

source/ArchitectureInDetail/DataAccessCommon.rst

Adding the RoutingDataSource with simple example. #1071

---

source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

(cherry picked from commit 166faf4 and 578f9f2 )
Please review #976.

[5.0.x]#976: fix typo about framework stack

---

source_en/Appendix/EnvironmentIndependency.rst

I translate to the English version.
Please review #1081 .

#1081: Add explanations of how to add external jar file into a web application's classpath on Tomcat 8. (English translation)

---

source_en/ArchitectureInDetail/Codelist.rst

I translate to English version.
Please review #1109 .

#1109: Add explanation of how to display a code name in CodeList.rst (English translation)

---

source/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst

* Add the Tomcat8
* Update the WebLogic version (12.1.1 -> 12.1.3)
* Add the JBoss EAP 6.4
* Remove the Resin
Please review #1172 .

#1172: Update description of DataSource provided by Application Server

---

source/ArchitectureInDetail/FileUpload.rst
source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

#1177: Update library versions for 1.0.3

---

source/Security/Authorization.rst
source_en/Security/Authorization.rst

#1003: Fix wrong usage for sec:authorize tag of jsp

---

source/ArchitectureInDetail/REST.rst
source/TutorialREST/index.rst
source_en/ArchitectureInDetail/REST.rst
source_en/TutorialREST/index.rst

#979: Implements Serializable interface in Resource class for REST API

---

source/ArchitectureInDetail/ExceptionHandling.rst
source/ArchitectureInDetail/Logging.rst
source/TutorialTodo/index.rst
source_en/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/Logging.rst
source_en/TutorialTodo/index.rst

#1176: Polish the logback settings

---

source/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst

* Add the Tomcat8
* Update the WebLogic version (12.1.1 -> 12.1.3)
* Add the JBoss EAP 6.4
* Remove the Resin
(cherry picked from commit e0388189f5a100ec8d9fdf50fe16a74674041cc6)
Please review #1172 .

[5.0.x] #1172: Update description of DataSource provided by Application Server

---

source_en/Appendix/EnvironmentIndependency.rst

[5.0.x] #1081: Add explanations of how to add external jar file into a web application's classpath on Tomcat 8. (English translation)

---

source/ArchitectureInDetail/ExceptionHandling.rst
source/ArchitectureInDetail/Logging.rst
source/TutorialTodo/index.rst
source_en/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/Logging.rst
source_en/TutorialTodo/index.rst

(cherry picked from commit f46d11fe499f59855e2eb4b73f68a8be4fe05db4)
Please review #1176 .

[5.0.x] #1176: Polish the logback settings

---

source/Security/Authorization.rst
source_en/Security/Authorization.rst

(cherry picked from commit a905c7bb09de070d665a182d37213f3f3df4c4f7)
Please review #1003 .

[5.0.x] #1003: Fix wrong usage for sec:authorize tag of jsp

---

source/ArchitectureInDetail/REST.rst
source/TutorialREST/index.rst
source_en/ArchitectureInDetail/REST.rst
source_en/TutorialREST/index.rst

(cherry picked from commit 185176bacb3e77d44dade4115406972182d6958b)
Please review #979 .

[5.0.x] #979: Implements Serializable interface in Resource class for REST API

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

#1076: Fix the package name of RedirectAuthenticationHandler

---

source/Appendix/CreateProjectFromBlank.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Security/Tutorial.rst
source/TutorialREST/index.rst
source/TutorialTodo/index.rst
source/index.rst
source_en/Appendix/CreateProjectFromBlank.rst
source_en/Overview/FrameworkStack.rst
source_en/index.rst

#1186: Update the TERASOLUNA version to 1.0.3.RELEASE

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

#1195: Add change logs for 1.0.3.RELEASE

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

#977: Add explanation about additivity attribute in Logging chapter

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

(cherry picked from commit 8d10741920e35651fc3d18d7bb4cf465d5a60a33)
Please review #1076 .

[5.0.x] #1076: Fix the package name of RedirectAuthenticationHandler

---

source/ArchitectureInDetail/Validation.rst
source_en/ArchitectureInDetail/Validation.rst

#1029: Fix wrong message definitions in Validation.rst

---

source_en/ArchitectureInDetail/DataAccessCommon.rst

#1071_Added Datasource Dynamic Switching Functionality

---

source/Appendix/ReferenceBooks.rst
source/Introduction/Introduction.rst
source_en/Appendix/ReferenceBooks.rst
source_en/Introduction/Introduction.rst

#1219: Add the Pro Spring 4th Edition as recommended books and reference books

---

source/Appendix/ReferenceBooks.rst
source/Introduction/Introduction.rst
source_en/Appendix/ReferenceBooks.rst
source_en/Introduction/Introduction.rst

[5.0.x] #1219: Add the Pro Spring 4th Edition as recommended books and reference books

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

I've added the change log about XML security vulnerability(CVE-2015-3192) for 1.0.3 release.
Please review #1195 .

#1195: Add change log about CVE-2015-3192 for 1.0.3.RELEASE

---

source_en/ArchitectureInDetail/DataAccessCommon.rst

(cherry picked from commit 83be0f3ae32ed8a37cb36b9f532af7f7a89cc317)
Please review #1071 .

[5.0.x] #1071_Added Datasource Dynamic Switching Functionality

---

source_en/Appendix/CreateProjectFromBlank.rst
source_en/Appendix/EnvironmentIndependency.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

#1146 Description about building war file

---

source_en/Appendix/CreateProjectFromBlank.rst
source_en/Appendix/EnvironmentIndependency.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

[5.0.x] #1146 Description about building war file

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

#1196: Add change logs for 5.0.1

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

[5.0.x] #1196: Add change logs for English version of 5.0.1

---

source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Pagination.rst

Please review #1244 .
まず日本語版を修正しました。日本語版マージ後に英語版に反映します。

#1244: Reflect specification changes of f:query

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

#1196: Add the change log about f:query

---

source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Pagination.rst

[5.0.x] #1244: Reflect specification changes of f:query

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

(cherry picked from commit a9aaab7b38109164bcbe6bf06ecc1e4b872e8e0e)
Please review #1196 .

[5.0.x] #1196: Add the change log about f:query

---

source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

#1146: Polishing

---

source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

(cherry picked from commit f8bcaaac73a87efc6763cbe44b12db7284b7b59d)
Please review #1146 .

[5.0.x] #1146: Polishing

---

source_en/Appendix/TagLibAndELFunctions.rst
source_en/ArchitectureInDetail/Pagination.rst

#1244: Reflect specification changes of f:query in English version

---

source_en/Appendix/TagLibAndELFunctions.rst
source_en/ArchitectureInDetail/Pagination.rst

[5.0.x] #1244: Reflect specification changes of f:query in English version

---

source/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/FileUpload.rst

#1253: Add JBoss EAP 6 into application server which use Commons FileUpload

---

source/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/FileUpload.rst

[5.0.x] #1253: Add JBoss EAP 6 into application server which use Commons FileUpload

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

Update change log #1260

---

conf/latexpdfen/ja2en.sh

#1270: Modify conversion target japanese string for note

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

#1274: Fixes wrong configuration file name of logback

---

source/ArchitectureInDetail/MessageManagement.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ArchitectureInDetail/MessageManagement.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

#1279: Update links of Java SE JavaDoc to 8

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

#1287: Update the link of SQL Maven Plugin

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

(cherry picked from commit 6341ab6eaafb27a6641e758d4df80490721f948a)
Please review #1287 .

[5.0.x] #1287: Update the link of SQL Maven Plugin

---

source/ArchitectureInDetail/Utilities/JodaTime.rst
source_en/ArchitectureInDetail/Utilities/JodaTime.rst

change DateTime To LocalDate. #1283

---

source/ArchitectureInDetail/SessionManagement.rst
source_en/ArchitectureInDetail/SessionManagement.rst

#1294: Improve how to replace a path variable at the time of redirect

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

add about sample test class and settings. #1284

---

source/ArchitectureInDetail/SessionManagement.rst
source_en/ArchitectureInDetail/SessionManagement.rst

(cherry picked from commit a25d2a145a422b1d18a86128110fbd92009dcf36)
Please review #1294 .

[5.0.x] #1294: Improve how to replace a path variable at the time of redirect

---

source/Security/Tutorial.rst
source_en/Security/Tutorial.rst

#1300: fix logout submit button

---

source/Security/Tutorial.rst
source_en/Security/Tutorial.rst

#1300  Fix logout submit button 
(cherry picked from commit 8dc7b5ddf6baa3b060d2364f4f32105f9228430d)

#1300: Fix logout submit button 

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

#1314: Improve description for @ControllerAdvice

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

(cherry picked from commit 0294191d6f1d8944cac1651cba5f689ed8d2dcab)
Please review #1314 .

[5.0.x] #1314: Improve description for @ControllerAdvice

---

source/ArchitectureInDetail/ExclusionControl.rst
source_en/ArchitectureInDetail/ExclusionControl.rst

#1312 
戻り値の方をStringからModelAndViewに修正。
修正しました。確認をお願いいたします。

fixed handlePessimisticLockingFailureException #1312

---

source_en/ArchitectureInDetail/SessionManagement.rst

[セッションスコープBeanの破棄について](https://github.com/terasolunaorg/guideline/issues/1198)の英訳追加です。

5.0.xへ「のセッションスコープBeanの破棄について」の改修反映

---

source/ArchitectureInDetail/ExceptionHandling.rst
source_en/ArchitectureInDetail/ExceptionHandling.rst

#1330: Add NoHandlerFoundException as exceptions which handled by DefaultHandlerExceptionResolver

---

source/ArchitectureInDetail/FileDownload.rst
source_en/ArchitectureInDetail/FileDownload.rst

[fix com.lowagie.itext version 4.2.1->2.1.7 ](https://github.com/terasolunaorg/guideline/pull/1334#discussion-diff-41479005) #1310 #1334
について、
5.0.xへバックポート

Issues/1310 fix itext version 5.0.x

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

#1358: Fix Sphinx build warning (html_static_path does not exist)

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

(cherry picked from commit 0be7243f99a6b37d9b6d9a910fe0a5502325b1ca)
Please review #1358 .

[5.0.x] #1358: Fix Sphinx build warning (html_static_path does not exist)

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

(cherry picked from commit 0be7243f99a6b37d9b6d9a910fe0a5502325b1ca)
Please review #1358 .

[1.0.x] #1358: Fix Sphinx build warning (html_static_path does not exist)

---

source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/Logging.rst
source/ArchitectureInDetail/Utilities/Dozer.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Introduction/ChangeLog.rst
source/Security/Authentication.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Utilities/Dozer.rst
source_en/ArchitectureInDetail/Validation.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst
source_en/Introduction/ChangeLog.rst
source_en/Security/Authentication.rst

#1352: Fix Sphinx warning(Duplicate explicit target name)

---

source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/Logging.rst
source/ArchitectureInDetail/Utilities/Dozer.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Introduction/ChangeLog.rst
source/Security/Authentication.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Utilities/Dozer.rst
source_en/ArchitectureInDetail/Validation.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst
source_en/Introduction/ChangeLog.rst
source_en/Security/Authentication.rst

(cherry picked from commit 86a6aeb2f76940360fddfaa58cb0883dec5c2464)
Please review #1352 .

[5.0.x] #1352: Fix Sphinx warning(Duplicate explicit target name)

---

.travis.yml

#1361: Add assertion script for detect build warning on travis-ci

---

.travis.yml

(cherry picked from commit 1face01bdfb4b71c3b26f8a1dbc66c56723dccc8)
Please review #1361 .

[5.0.x] #1361: Add assertion script for detect build warning on travis-ci

---

source/ArchitectureInDetail/SessionManagement.rst

#1306 
該当箇所（2か所に大別される）にて
jspでセッションスコープのBeanを参照している箇所を、すべてSpEL式を用いた参照に置き換えた。
それに伴ってView(JSP)からsessionスコープのBeanを参照する方法を追記し、その他の説明文の該当箇所も修正した。
・項番がズレていたので修正した

#1306 refer session scope

---

CONTRIBUTING.md

Change rule for git commit comment #1377

---

source/ArchitectureInDetail/Validation.rst

「Ag」を「Age」に修正いたしました。
ご確認をよろしくお願いいたします。 #1375

modify Ag to Age #1375

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

ソース(src/main/webapp/WEB-INF/views/login.jsp)の項番を(1)から採番し、
説明の項番もそれにあわせて修正しました。
英語版も修正いたしました。
ご確認をよろしくお願いいたします。
#1376

modify source and description Sr.No. #1376

---

source/ArchitectureInDetail/SessionManagement.rst

Polishing description about SpEL.
Please review #1306 .

Polishing description about SpEL #1306

---

source/ArchitectureInDetail/SessionManagement.rst

[5.0.x] Refer session scoped bean by SpEL #1306

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

Fix typo at method return type in ApplicationLayer.rst #1394

---

source/Security/Tutorial.rst

Fix typo in Spring Security Tutorial #1374

---

source/ArchitectureInDetail/DataAccessJpa.rst
source/TutorialTodo/index.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst
source_en/TutorialTodo/index.rst

Change default value of 'hibernate.hbm2ddl.auto' ('none' -> '') #1282

---

source/ArchitectureInDetail/Validation.rst

I've polished some description sentence. And this PR includes reflecting changes of terasolunaorg/terasoluna-gfw#397 .
Please review #1389 .

Modify support class on @ByteMin and @ByteMax (String -> CharSequence) #1389

---

.travis.yml

Change a timing of displaying error logs on travis CI #1417

---

.travis.yml

(cherry picked from commit 59e7eb7aa719866a26dd971f3e51017b68b2c510)
Please review #1417 .

[5.0.x] Change a timing of displaying error logs on travis CI #1417

---

source_en/ImplementationAtEachLayer/ApplicationLayer.rst

#1339 Translated SpringMVC url description

---

source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

#1343 Described application development in offline environment

---

source/ArchitectureInDetail/Validation.rst

I reflected the changes of https://github.com/terasolunaorg/terasoluna-gfw/pull/410 to guideline.
Please review #1389 to check 98682b6eb6f720e43fac1d4d878c55d45f484542, and Please merge after pull request #1432.

Change attribute name of @Compare #1389

---

source/ArchitectureInDetail/Validation.rst

I reflected the changes of https://github.com/terasolunaorg/terasoluna-gfw/pull/406 to guideline.
Please review #1389.

Reflect guide to improve compare annotation #1389

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst

Add how to specify a defaultFetchSize #965

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst

Add how to flush sql statements on batch mode #915

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Modify to use generic type in ResultHandler #1384

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Change default library for generating proxy object in MyBatis3 (CGLIB -> JAVASSIST) #1384

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

#1275: Update logback configuration priorities

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Add @NoRepositoryBean annotation on inheriting a common project Repository interface

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Please review #1444 
This is a backport of #1445 
(cherry picked from commit 1e15ddcb6a25c4c151adb5571e61a597abbe98cd)

[5.0.x] Add @NoRepositoryBean annotation on inheriting a common project Repository interface #1444

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

@Order  の指定が任意であることを記載しました。
ご確認お願い致します。 #1315

mod @Order explanation. #1315

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

5.0.xにバックポートしました。
ご確認お願い致します。
#1315

Issues/1315 mod order annotation #1315 

---

source/ArchitectureInDetail/Validation.rst

Please review and merge #1453.

Correct typo, and improve validation message #1453

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

(cherry picked from commit d25e96768a805a12e4125cc62825b8e079955c11)
Please review #1275.

[5.0.x] #1275: Update logback configuration priorities

---

source/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/REST.rst

Implemented in JP version only.
Once JP version is confirmed, accordingly will update English version too.
Request you to review #1323

updated infra and domain layer code #1323

---

source/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/REST.rst

Cherry-pick to 5.0.x of #1323 
Please review.

Updated infra and domain layer code for REST API to 5.0.x

---

source/ArchitectureInDetail/RestClient.rst

add Apache Http Client guide. #1477

---

source/ArchitectureInDetail/Utilities/StringProcessing.rst
source/ArchitectureInDetail/Utilities/index.rst

Add String operations(halfwidth-fullwidth conversion, code points check) #1406 #1451 

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst

add description @init-DB #1428

---

source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

#1442 Translated how to specify default fetchsize

---

source/ArchitectureInDetail/Codelist.rst
source/ArchitectureInDetail/Validation.rst

I will reflect this changes on English version after merging #1448 . 
Please review #1486 .

Reflect specification change for support CharSequence on @ExistInCodeList #1486

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

Fixes typos in Authentication.rst #1482

---

source/ArchitectureInDetail/Codelist.rst

remove ``<property name="jdbcTemplate" ref="jdbcTemplateForCodeList" /> ``
Please review #501 .

remove jdbcTemplate definition #501

---

source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

#1443 Translated how to flush statements on batch mode

---

source/ArchitectureInDetail/SOAP.rst

Improve SOAP guideline

---

source/ArchitectureInDetail/SOAP.rst

Added caption and moved description position.
Please review #1340 .

Add caption in development using Tomcat #1340

---

source/ArchitectureInDetail/REST.rst

[5.0.x] Improve how to define ObjectMapper of Jackson #1022

---

source_en/ArchitectureInDetail/SessionManagement.rst

#1455 How to refer Session-scoped Bean

---

source_en/ArchitectureInDetail/SessionManagement.rst

Conflicts:
source_en/ArchitectureInDetail/SessionManagement.rst
Cherry-pick to 5.0.x version.
Please review #1455

#1455 How to refer Session-scoped Bean to 5.0.x (cherry picked from commit 03915d507f8d392e08af06fca8552d966291c13b)

---

source_en/ArchitectureInDetail/Validation.rst

#1448 Added new constraints of Bean validation

---

source/ArchitectureInDetail/Validation.rst

I've added introduction of `@ConsistOf` annotation in common library annotations list.
Please review and merge #1389.

Add introduction of @ConsistOf #1389

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Please review #1327
Japanese as well English version modified.

#1327 DateTimeProvider extension bug fixing

---

source/ArchitectureInDetail/DataAccessJpa.rst

Please review #1326 
Below implementation is compatible with 5.1.0 milestone means compatible with Spring-data-commons 1.11.0.RELEASE version but not sure about 5.0.2 milestone.

#1326 Adding custom method to all reposotories

---

source/ArchitectureInDetail/DoubleSubmitProtection.rst

Add a description of the namespace attribute #1487

---

source/ArchitectureInDetail/Validation.rst

Please review and merge #1531.

improve validation messages #1531

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Please review #1327 which is cherry-pick to 5.0.x

Issues/1327 date time provider extension 5.0.x

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Please review #1463.
Japanese as well English are modified.
After merging backport is required.

#1463 updated annotation

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Please review #1464.
Japanese as well English are modified.
After merging backport is required.

#1464 Modified the wrong utility

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

Please review #1525.
Japanese as well English are modified.
After merging backport is required.

#1525 Fixing incorrect boolean value set

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

(cherry picked from commit a49976ba977ff659df55a416988820c4fe7b71d3)
Backport to 5.0.x
Please review #1463

[5.0.x] #1463 updated annotation

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

Update copyright year to 2016 #1466

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

(cherry picked from commit 2f7b3ec1a809dcb54bca4e792e3931f9d4060ed1)
Please review #1466 .

[5.0.x] Update copyright year to 2016 #1466

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

[1.0.x] Update copyright year to 2016 #1466

---

source/ArchitectureInDetail/Validation.rst

please review. #1493 
https://github.com/terasolunaorg/guideline/commit/16a1acf30542d4b649b5f2395cf1fdc1e641f2c0

Hibernate Validator Warning delete #1493

---

source/ArchitectureInDetail/Utilities/StringProcessing.rst

add string operations #1451

---

source/ArchitectureInDetail/Internationalization.rst

modify discriotion of locale i18n #686

---

source/ArchitectureInDetail/Logging.rst
source/ArchitectureInDetail/REST.rst
source/Overview/FirstApplication.rst
source/TutorialREST/index.rst
source/TutorialTodo/index.rst

correspond to the 'Spring Security 4.0.' #1519

---

source/ArchitectureInDetail/Utilities/DateAndTime.rst
source/ArchitectureInDetail/Utilities/JodaTime.rst
source/ArchitectureInDetail/Utilities/index.rst

add date operations #1450

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

---
please review #1524.
26b5cedcfa042f7434d970e50ccf65e90e3c358b
84ac8ca7daa822f220a2dc0e78bb209360963e91
---

NumberFormat-style only link to javadoc #1524

---

Makefile
make.bat

#1504
change only makefile for pdf error

change only makefile for pdf error #1504

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Please review #1384 .
backport of #1387(using generic-type for ResultHandler) , and #1388(Change default library for generating proxy object in MyBatis3 to JAVASSIST, and note how to user CGLIB) .

[5.0.x] reflect changes of my batis3.3.0 #1384

---

source/Security/PasswordHashing.rst

[5.0.x] fix incorrect workaround for securerandom delayng #1502

---

source_en/Security/PasswordHashing.rst

fix incorrect workaround for securerandom delayng (en) #1502

---

source/ArchitectureInDetail/FileDownload.rst

add exclusions #1574

---

source/Overview/FrameworkStack.rst

[1.0.x]FrameworkStack version update. #1596

---

source/Overview/FrameworkStack.rst

[5.0.x]FrameworkStack version update. #1596

---

source_en/Overview/FrameworkStack.rst

[1.0.x]FrameworkStack version update.(en) #1596

---

source_en/Overview/FrameworkStack.rst

[5.0.x]FrameworkStack version update.(en) #1596

---

source_en/Overview/FrameworkStack.rst

[master]FrameworkStack version update.(en) #1596

---

source/Introduction/ChangeLog.rst

----
#1469  
4a28448c5450cdc66fac2ec8f00b149de5706433
----

change log  -> 1.0.4 #1469

---

source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Please merge #1662.
It has occurred during [this change](https://github.com/terasolunaorg/guideline/pull/1501/files#diff-d94e8c7bbddb884b74d8acbf6a682ee2R5859).

Resolve rst build error #1662

---

source/Introduction/ChangeLog.rst

----
#1468 
59f9690331319286f5ad4838e355850de2b7f0c4
----

change log -> 5.0.2 #1468

---

.travis.yml

Add 'ERROR' at assertion script #1361

---

source/Introduction/ChangeLog.rst

----
#1467 
08610ec907546e2261171148984e4d01e912f83a
ecbfa9b1b636260b911851a37ceeeacd49c05ffd
236f73e275e3248ba465e5e634de5da8263fd9b9
----

change log ->5.1.0

---

source/Appendix/CreateProjectFromBlank.rst
source/Appendix/Nexus.rst
source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Codelist.rst
source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/DataAccessJpa.rst
source/ArchitectureInDetail/DataAccessMyBatis3.rst
source/ArchitectureInDetail/ExclusionControl.rst
source/ArchitectureInDetail/FileDownload.rst
source/ArchitectureInDetail/FileUpload.rst
source/ArchitectureInDetail/PropertyManagement.rst
source/ArchitectureInDetail/REST.rst
source/ArchitectureInDetail/SystemDate.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Overview/ApplicationLayering.rst
source/Overview/FirstApplication.rst
source/Overview/SpringMVCOverview.rst
source/Security/Authentication.rst
source/Security/Authorization.rst
source/Security/CSRF.rst
source/Security/SpringSecurity.rst
source/Security/Tutorial.rst
source/TutorialTodo/index.rst
source/index.rst

Please review #1597
マージは他の pull request の後でします。

[5.0.x]Verify and update external URL Links #1597

---

.travis.yml

(cherry picked from commit 966fcc45d351e61fed97552bcf889aaa8e3bf091)
please review #1361 .

[5.0.x] Add 'ERROR' at assertion script #1361

---

source/Appendix/CreateProjectFromBlank.rst
source/Appendix/Nexus.rst
source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Codelist.rst
source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/DataAccessJpa.rst
source/ArchitectureInDetail/FileDownload.rst
source/ArchitectureInDetail/FileUpload.rst
source/ArchitectureInDetail/PropertyManagement.rst
source/ArchitectureInDetail/REST.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Overview/ApplicationLayering.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Overview/SpringMVCOverview.rst
source/Security/Authentication.rst
source/Security/Authorization.rst
source/Security/CSRF.rst
source/Security/SpringSecurity.rst
source/Security/Tutorial.rst
source/TutorialREST/index.rst
source/TutorialTodo/index.rst
source/index.rst

Please review #1597
マージは他の pull request の後でします。

[1.0.x]Verify and update external URL Links #1597

---

source/Appendix/CreateProjectFromBlank.rst
source/Appendix/Nexus.rst
source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Codelist.rst
source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/DataAccessJpa.rst
source/ArchitectureInDetail/DataAccessMyBatis3.rst
source/ArchitectureInDetail/Email.rst
source/ArchitectureInDetail/ExclusionControl.rst
source/ArchitectureInDetail/FileDownload.rst
source/ArchitectureInDetail/FileUpload.rst
source/ArchitectureInDetail/PropertyManagement.rst
source/ArchitectureInDetail/REST.rst
source/ArchitectureInDetail/RestClient.rst
source/ArchitectureInDetail/SOAP.rst
source/ArchitectureInDetail/SystemDate.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Overview/ApplicationLayering.rst
source/Overview/FirstApplication.rst
source/Overview/SpringMVCOverview.rst
source/index.rst

Please review #1597
マージは他の pull request の後でします。

Verify and update external URL Links #1597

---

source/Introduction/ChangeLog.rst

リリース前最終確認により上がった軽微な修正 #1676

---

source/Introduction/ChangeLog.rst

[5.0.x]リリース前最終確認により上がった軽微な修正 #1676

---

source/ArchitectureInDetail/REST.rst

(cherry picked from commit 8ccc782e3b0a6e07f425b3c772519ae7bf82d63a)
@ikeyat さん、masterに実施した内容を5.1.0.RELEASEにバックポートしました。 #1680
ご確認よろしくお願いします。

Modified index of PDF for 5.1.0.RELEASE guideline. #1680

---

source_en/ArchitectureInDetail/Codelist.rst

Please review #1494 for merging to translation/5.0.2

Issues/1494 inject jdbc template into jdbc codelist tran 5.0.2

---

source_en/ArchitectureInDetail/Codelist.rst

Please review #1494 for merging to 5.0.x

Issues/1494 inject jdbc template into jdbc codelist tran 5.0.x

---

source_en/ArchitectureInDetail/Codelist.rst

Please review #1494 for merging to 5.1.x

Issues/1494 inject jdbc template into jdbc codelist tran 5.1.x

---

source_en/ArchitectureInDetail/DoubleSubmitProtection.rst

Please review #1529.
(cherry picked from commit ad94a7b2af93bc3ba4f8ad01a16a780f90e81502)

#1529 Apply support @AliasFor in @TransactionTokenCheck

---

source_en/ArchitectureInDetail/FileDownload.rst

Please review #1551
(cherry picked from commit 1524aeea96feeb706717dde77d7d6534c58cca25)

#1551 Update how to download Excel file

---

source_en/ArchitectureInDetail/Utilities/StringProcessing.rst
source_en/ArchitectureInDetail/Utilities/index.rst

#1559 Added string operations

---

source_en/ArchitectureInDetail/Codelist.rst

Please review #1560.
(cherry picked from commit 351867a6e85aade7ded607ebfedf9e3e7181fd53)

#1560 Apply SupportCharSequence on @ExistInCodeList

---

source_en/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/REST.rst
source_en/Overview/FirstApplication.rst
source_en/TutorialREST/index.rst
source_en/TutorialTodo/index.rst

#1570 Apply spring security 4

---

source_en/ArchitectureInDetail/Validation.rst

Please review #1523.
(cherry picked from commit 6927ca2ca6eeb10d60c3f389e393132c509c2b4f)

#1523 Added Introduction of @ConsistOf

---

source_en/ArchitectureInDetail/DataAccessCommon.rst

Please review #1589.
(cherry picked from commit d42dc5f5147346c4c5425b1b4e1aa4734180953d)

#1589 Added warn comment on log4jdbc datasource in prod

---

source_en/ArchitectureInDetail/Internationalization.rst

Please review #1576.
(cherry picked from commit 68744799d15ab8bd134d7f36eb8f470ea8a68bf1)

#1576 Modified description of Locale

---

source_en/ArchitectureInDetail/REST.rst

Please review #1594.
(cherry picked from commit 0d0c28942ac74aded1bffa954bf976d6c1d49151)

#1594 Sample modification of Error handling in RESTful Web Service

---

source_en/ArchitectureInDetail/FileUpload.rst

Please review #1609.
(cherry picked from commit 5c57ce9ff76c0e1525db63f63a3409ed9ff2af25)

#1609 Deprecated specifications commons file upload

---

source_en/ArchitectureInDetail/RestClient.rst

Please review #1638
(cherry picked from commit 0556facba9cc7127271431f19a429228538e30f1)

#1638 Add dependency spring-web lib for RestClient

---

source_en/ArchitectureInDetail/FileDownload.rst

Please review #1632
(cherry picked from commit d2b7dbbfc294f03357dffc69db84ce9b7e19576a)

#1632 Added exclusion tag to dependency tag

---

source_en/ArchitectureInDetail/FileUpload.rst

Please review #1639
Conflicts:
source_en/ArchitectureInDetail/FileUpload.rst

#1639 Reflected results of Servlet3.0 upload verification in WebLogic

---

source_en/Security/Encryption.rst

#1641 Added description of JDK8 class use

---

source_en/ArchitectureInDetail/REST.rst

#1648 Added JsonView

---

source_en/ArchitectureInDetail/FileUpload.rst
source_en/Security/CSRF.rst

Please review #1667.
This is cherry-pick to translation/5.0.2
Conflicts:
source_en/Security/CSRF.rst

#1667 Multipart request fixing

---

source_en/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/SOAP.rst
source_en/TutorialREST/index.rst
source_en/TutorialTodo/index.rst

Please review #1645.
Reflect Eng #1622 (remove 'auto-config' and correspond to spring security 4) #1645

remove auto config and correspond to spring security 4 #1645

---

source_en/Introduction/ChangeLog.rst

Please review #1669.
This is cherry-pick to 5.0.x
(cherry picked from commit 25b4d5ca9840c16e0d425ecfaaf871c199144731)

#1669 Added change log for 5.0.2

---

source_en/Introduction/ChangeLog.rst

Please review #1668.
This is cherry-pick to translation/5.1.x

#1668 Added change log for 5.1.0

---

source_en/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/SOAP.rst
source_en/TutorialREST/index.rst
source_en/TutorialTodo/index.rst

Please review #1645.
This is cherry-pick to 5.1.x
(cherry picked from commit fc6046ec8bb758090190dd7661f4ff21e72108f8)

remove auto config and correspond to spring security 4 Backport For 5.1.x #1645

---

source_en/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/REST.rst
source_en/ArchitectureInDetail/SOAP.rst
source_en/TutorialREST/index.rst
source_en/TutorialTodo/index.rst

Please review #1645.
(cherry picked from commit fc6046ec8bb758090190dd7661f4ff21e72108f8)

remove auto config and correspond to spring security 4 Backport For translation/5.1.0 #1645

---

source_en/ArchitectureInDetail/REST.rst

mod not enough quot REST.rst for translation/5.0.2 #1829

---

Makefile

Pleave review #1838 
This is pull request to translation/5.1.0 branch

#1838 build path of pdf creation

---

source_en/ArchitectureInDetail/REST.rst

This is cherry-pick to master
(cherry picked from commit 7a7ed41cddcc6d763539f81724c2fcc73b56f2b1)

mod not enough quot REST.rst for master #1829

---

source_en/ArchitectureInDetail/REST.rst

(cherry picked from commit 7a7ed41cddcc6d763539f81724c2fcc73b56f2b1)

mod not enough quot REST.rst for translation/5.1.0 #1829

---

source_en/ArchitectureInDetail/REST.rst

This is cherry-pick to 5.1.x
(cherry picked from commit 7a7ed41cddcc6d763539f81724c2fcc73b56f2b1)

mod not enough quot REST.rst for 5.1.x #1829

---

source_en/ArchitectureInDetail/REST.rst

This is cherry-pick to 5.0.x
(cherry picked from commit 7a7ed41cddcc6d763539f81724c2fcc73b56f2b1)

mod not enough quot REST.rst for 5.0.x #1829

---

Makefile

Pleave review #1838 
This is pull request to 5.1.x
(cherry picked from commit b7412557f10495059191b19a40e2da756e10bab9)

#1838 Fixing build path of pdf creation

---

source_en/ArchitectureInDetail/Internationalization.rst
source_en/ArchitectureInDetail/index.rst

Please review #1850.
Japanese exist in English Guideline #1850
but, 5.1.x only.

mod Japanese exist in English Guideline for 5.1.x #1850

---

source_en/ArchitectureInDetail/Internationalization.rst
source_en/ArchitectureInDetail/index.rst

Please review #1850.
Japanese exist in English Guideline #1850 
This is cherry-pick to master
(cherry picked from commit e8c286d4f207b5a9a572ab379b287b22a4cbe3ae)

mod Japanese exist in English Guideline for master #1850

---

source_en/ArchitectureInDetail/Internationalization.rst
source_en/ArchitectureInDetail/index.rst

Please review #1850.
Japanese exist in English Guideline #1850 
This is cherry-pick to release/5.1.0.RELEASE
(cherry picked from commit  e8c286d )

mod Japanese exist in English Guideline for release/5.1.0.RELEASE #1850

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Add issue and PR template. Modify url at CONTRIBUTING.md #1696

---

source/ArchitectureInDetail/Utilities/StringProcessing.rst

Add description to add a dependency of terasoluna-gfw-string #1699

---

source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Fixes typos in DataAccessMyBatis3.rst #1858

---

source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Please review #1858.(backport)

Fixes typos in DataAccessMyBatis3.rst #1858(backport)

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

Issues/1830 not enough quot 5.1.x #1830

---

source/TutorialTodo/index.rst
source_en/TutorialTodo/index.rst

Fix TutorialTodo/index.rst to clerical corrections #1872

---

source/ArchitectureInDetail/ExceptionHandling.rst

Fixed Typo ExceptionHandling sample code #1747

---

source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Please review #1886 
Added a whitespaces at the missing places.

Fix Typos from Mybatis #1886

---

source/ArchitectureInDetail/Utilities/DateAndTime.rst
source/ArchitectureInDetail/Utilities/JodaTime.rst
source_en/ArchitectureInDetail/Utilities/DateAndTime.rst
source_en/ArchitectureInDetail/Utilities/JodaTime.rst

Please review #1748.
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Utilities/JodaTime.html#id20も4か所修正しました。ご確認お願いします。
firstDayOfCalender　 -> firstDayOfCalendar
lastDayOfCalender    -> lastDayOfCalendar

Fixes typos in JodaTime.rst #1748

---

source/ArchitectureInDetail/WebServiceDetail/RestClient.rst

Please review #1856.
Changed Appendix RestClientProxySettings in source/ArchitectureInDetail/RestClient.rst.

Change the HTTP Proxy Server Setting in RestClient from System Property to ClientHttpRequestFactory #1856

---

source/ArchitectureInDetail/RestClient.rst

Please review #1856 .
(Backport from #1862 by cherry-pick.)

[5.1.x] Change the HTTP Proxy Server Setting in RestClient from System Property to ClientHttpRequestFactory #1856

---

source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst

Please review #1699.
(https://github.com/terasolunaorg/guideline/pull/1855#discussion_r59487152)

change paragraph about common library #1699

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md

add a changelog text to CONTRIBUTE.md #1696

---

source/ArchitectureInDetail/Utilities/StringProcessing.rst

add desc dependency string (backport 5.1.x) #1699

---

source/ArchitectureInDetail/Utilities/DateAndTime.rst
source/ArchitectureInDetail/Utilities/JodaTime.rst
source_en/ArchitectureInDetail/Utilities/DateAndTime.rst
source_en/ArchitectureInDetail/Utilities/JodaTime.rst

Please review #1748.(backport)

Fix typo in joda time(5.1.x) #1748

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/Overview/FrameworkStack.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/Overview/FrameworkStack.rst

resolving the problem (wrong and duplicated information spring io pf) #1900

---

source/Tutorial/TutorialTodo.rst

fix the unordered serial number (TutorialTodo) #1895 

---

source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/Overview/FrameworkStack.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/Overview/FrameworkStack.rst

resolving the problem (wrong and duplicated information spring io pf) backport to 5.1.x  #1900 

---

source/TutorialTodo/index.rst

fix the unordered serial number backport to 5.1.x #1895

---

source/ArchitectureInDetail/DoubleSubmitProtection.rst
source_en/ArchitectureInDetail/DoubleSubmitProtection.rst

modifyed clerical errors of the Jpn and Eng sources (backport) #1898

---

source/TutorialREST/index.rst

modify the mistake in numbering (backport) #1891

---

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst

change DataAccessMyBatis3.rst  Line1246.#1916

---

source/TutorialTodo/index.rst

Please review #1836 .
(this is the backport of  #1902 )

modify reading doc and tutorial backport to 5.1.x  #1836

---

source/ArchitectureInDetail/DataAccessDetail/ExclusionControl.rst
source_en/ArchitectureInDetail/ExclusionControl.rst

1694_Fix_ExclusionControl.rst_adding_warring_messages

---

source/ArchitectureInDetail/ExclusionControl.rst
source_en/ArchitectureInDetail/ExclusionControl.rst

[5.1.x] Fix ExclusionControl.rst adding warring messages #1694

---

source/Appendix/SpringComprehensionCheck.rst
source/ArchitectureInDetail/Email.rst
source/ArchitectureInDetail/MessageManagement.rst
source/Security/CSRF.rst
source_en/Appendix/SpringComprehensionCheck.rst
source_en/ArchitectureInDetail/Email.rst
source_en/ArchitectureInDetail/MessageManagement.rst
source_en/Security/CSRF.rst

Please review #1879.
(backport to 5.1.x )

modify warning on sphinx build backport to 5.1.x #1879

---

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst

fix usage of DataAccessMyBatis3.rst #1930

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst

Please review #1930 .
(cherry picked from commit ff76bcc1d2031a0fe814c471a8c12bfbf5036f07)

5.1.x_backport fix usage of DataAccessMyBatis3.rst #1930

---

source/ArchitectureInDetail/Utilities/StringProcessing.rst
source/Introduction/ChangeLog.rst

Please review #1914 .
(backport 5.1.X)

Issues/#1914 backport 5.1.x add description jisx 0208 codepoints

---

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst

Please review #994 .
I couldn't find same functions in Bean Validation(Hibernate Validator).I added with the possible solution.

add reading a Bean Validation messagewith  MessageSource #994

---

source/ArchitectureInDetail/Validation.rst

Please review #994.
I counldn't cherry-pick automatically. I backported manually.

add reading a Bean Validation messagewith MessageSource (backport to 5.1.x) #994

---

source/ArchitectureInDetail/WebApplicationDetail/Internationalization.rst

Fix_Description_of_paramName_in_LocaleChangeInterceptor.#1354

---

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst

modified wrong discription of ValidationMessages.properties. #1948

---

source/ImplementationAtEachLayer/DomainLayer.rst

Add_Note_Transactional_timeout.#1777

---

source/ImplementationAtEachLayer/DomainLayer.rst

[5.1.x]Add_Note_Transactional_timeout.#1777

---

source/ArchitectureInDetail/WebApplicationDetail/DoubleSubmitProtection.rst
source/Introduction/ChangeLog.rst

remove TransactionTokenContext Description. #1995

---

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst

#1292_Remove_Note_SqlsessionTemplate_warn_log_controlled

---

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
source/Introduction/ChangeLog.rst

Please review #1965.
Investigation result is here.
https://github.com/terasolunaorg/guideline/issues/1965#issuecomment-231950594

modify http response header #1965

---

source/ArchitectureInDetail/MessageManagement.rst
source/Security/Authentication.rst
source/Security/Tutorial.rst
source_en/ArchitectureInDetail/MessageManagement.rst
source_en/Security/Authentication.rst
source_en/Security/Tutorial.rst

Change param.error to param.containsKey('error') #1963

---

source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst
source/Introduction/ChangeLog.rst
source/Security/Authentication.rst
source/Tutorial/TutorialSecurity.rst
source_en/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst
source_en/Security/Authentication.rst
source_en/Tutorial/TutorialSecurity.rst

Remove Note By Spring Security 4.0.3 #1963

---

source/ArchitectureInDetail/DoubleSubmitProtection.rst
source/Introduction/ChangeLog.rst

Please review #1995 .
(cherry picked from commit 882072c834d97bb2886b112e99ebff82bab3c9f2)

[5.1.x] remove TransactionTokenContext Description. #1995

---

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst

Add Warning of Method Validation.#1998

---

source/ArchitectureInDetail/Validation.rst

[5.1.x]Add Warning of Method Validation.#1998

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

add warninng DateTimeFormat's formatter is not strict #1991

---

source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

Issues/[5.1.x_backport]1991 date time format is not strict with jsr310 for 5.1.x

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

add JSR310 corresponding for ChangeLog #1991

---

source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

Please review #1991 
(cherry picked from commit 4f8ebfa3332c147dc696f6eac1b82aa7b93d9a09)
Conflicts:
source/Introduction/ChangeLog.rst
source_en/Introduction/ChangeLog.rst

[5.1.x_backport]add JSR310 corresponding #1991

---

source/Appendix/ReferenceBooks.rst
source_en/Appendix/ReferenceBooks.rst

add 「Spring thorough guide」 at reference books #2043

---

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst

update error word #2026

---

source/Security/Authorization.rst

add workaround for CVE-2016-5007 #1976

---

source/Security/Authorization.rst

write workaround for cve-2016-5007 #1976

---

source/Security/Authorization.rst

[5.1.x_backport] write workaround for cve-2016-5007 #1976

---

source/Security/Authorization.rst

[5.0.x_backport] write workaround for cve-2016-5007 #1976

---

source/ArchitectureInDetail/WebServiceDetail/SOAP.rst

#2007_Add_status_code_at_the_time_of_web_service_exception_occurs

---

source/Security/Authorization.rst

[1.0.x_backport] write workaround for cve-2016-5007 #1976

---

source/ArchitectureInDetail/SOAP.rst

[5.1.x backport] #2007 add discription status code at the time of web service exception occurs backport 5.1.x

---

source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst

English translation for addition of string2 dependency #1911

---

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst

Translation of the Date and time format validation #1927

---

source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

[5.1.x]raise_mybatis_and_mybatis-spring_version.#2020

---

source/Appendix/TagLibAndELFunctions.rst
source/ArchitectureInDetail/Codelist.rst
source/ArchitectureInDetail/DataAccessCommon.rst
source/ArchitectureInDetail/FileDownload.rst
source/ArchitectureInDetail/FileUpload.rst
source/ArchitectureInDetail/PropertyManagement.rst
source/ArchitectureInDetail/REST.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source/ImplementationAtEachLayer/DomainLayer.rst
source/Introduction/ChangeLog.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Overview/SpringMVCOverview.rst
source/Security/Authorization.rst
source/TutorialTodo/index.rst
source_en/Overview/FrameworkStack.rst

[1.0.x]raise_Spring_Framework_version_to_3.2.17.#2020

---

source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

add_spring-jms#1992

---

source/ArchitectureInDetail/WebServiceDetail/RestClient.rst

Please review #1856.
This modification is the answer to the following comment.
* https://github.com/terasolunaorg/guideline/pull/1862/files#r68407693
* https://github.com/terasolunaorg/guideline/pull/1862/files#r68409504
* https://github.com/terasolunaorg/guideline/pull/1862/files#r68409946

Add description of the setting of the Proxy in SimpleClientHttpRequestFactory.#1856

---

source/ArchitectureInDetail/RestClient.rst

Please review #1856.
Cherry-picked form #2066.

[5.1.x] Add description of the setting of the Proxy in SimpleClientHttpRequestFactory.#1856

---

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
source/ArchitectureInDetail/GeneralFuncDetail/SystemDate.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Tutorial/TutorialSecurity.rst
source/Tutorial/TutorialTodo.rst
source_en/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/GeneralFuncDetail/SystemDate.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/Overview/FirstApplication.rst
source_en/Overview/FrameworkStack.rst
source_en/Tutorial/TutorialSecurity.rst
source_en/Tutorial/TutorialTodo.rst

check and update version num #2076

---

source/Appendix/CreateProjectFromBlank.rst
source/ArchitectureInDetail/DataAccessMyBatis3.rst
source/ArchitectureInDetail/SystemDate.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Security/Tutorial.rst
source/TutorialTodo/index.rst
source_en/Appendix/CreateProjectFromBlank.rst
source_en/ArchitectureInDetail/DataAccessMyBatis3.rst
source_en/ArchitectureInDetail/SystemDate.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/Overview/FirstApplication.rst
source_en/Overview/FrameworkStack.rst
source_en/Security/Tutorial.rst
source_en/TutorialTodo/index.rst

check and update version for 5.1.1 #2076

---

source/Appendix/CreateProjectFromBlank.rst
source/Overview/FirstApplication.rst
source/Overview/FrameworkStack.rst
source/Security/Tutorial.rst
source/TutorialREST/index.rst
source/TutorialTodo/index.rst
source_en/Overview/FrameworkStack.rst

check and update version #2076

---

source/ArchitectureInDetail/FileUpload.rst

[5.1.x] Modify set commions-fileupload version.#1973

---

source/ArchitectureInDetail/FileUpload.rst
source/Introduction/ChangeLog.rst

[1.0.x] Issues/1973 add warning commions fileupload backport 1.0.x

---

source/Appendix/ReferenceBooks.rst
source/ArchitectureInDetail/DataAccessDetail/DataAccessJpa.rst
source/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst
source/ArchitectureInDetail/WebApplicationDetail/Validation.rst
source/ImplementationAtEachLayer/CreateProject.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/Security/Encryption.rst
source/Security/SecureLoginDemo.rst
source_en/Appendix/ReferenceBooks.rst
source_en/ArchitectureInDetail/GeneralFuncDetail/StringProcessing.rst
source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst
source_en/ImplementationAtEachLayer/CreateProject.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/Security/Encryption.rst
source_en/Security/SecureLoginDemo.rst

modify invalid hyperlinks.#2052

---

source/Appendix/EnvironmentIndependency.rst
source/Appendix/ReferenceBooks.rst
source/ArchitectureInDetail/DataAccessJpa.rst
source/ArchitectureInDetail/Utilities/StringProcessing.rst
source/ArchitectureInDetail/Validation.rst
source/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source/Security/Encryption.rst
source/Security/SecureLoginDemo.rst
source_en/Appendix/EnvironmentIndependency.rst
source_en/Appendix/ReferenceBooks.rst
source_en/ArchitectureInDetail/Utilities/StringProcessing.rst
source_en/ArchitectureInDetail/Validation.rst
source_en/ImplementationAtEachLayer/CreateWebApplicationProject.rst
source_en/Security/Encryption.rst
source_en/Security/SecureLoginDemo.rst

[5.1.x]modify invalid hyperlinks #2052

---

source/index.rst
source_en/index.rst

Add issue and PR template(Modify url at index.rst.)#1696

---

source/Appendix/ReferenceBooks.rst
source_en/Appendix/ReferenceBooks.rst
source_en/ArchitectureInDetail/Codelist.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/FileDownload.rst
source_en/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/PropertyManagement.rst
source_en/ArchitectureInDetail/Validation.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ImplementationAtEachLayer/DomainLayer.rst
source_en/Overview/FirstApplication.rst
source_en/Overview/FrameworkStack.rst
source_en/Overview/SpringMVCOverview.rst
source_en/Security/Authorization.rst
source_en/Security/SpringSecurity.rst
source_en/TutorialTodo/index.rst

[1.0.x]modify invalid Hyperlinks.#2052

---

source/Introduction/ChangeLog.rst

add change log for 5.2.0 #2038

---

source/Introduction/ChangeLog.rst

Add change logs for 5.1.1 #2039

---

source/Introduction/ChangeLog.rst

add change log for 1.0.5 #2075

---

source/Introduction/ChangeLog.rst

add change log for 5.0.3 #2106

---

source/Introduction/Introduction.rst
source_en/Introduction/Introduction.rst

add reference to Spring Tettei Nyuumonn in introduction #2043

---

source/Introduction/Introduction.rst
source_en/Introduction/Introduction.rst

Please review #2043 .
(cherry picked from commit 20cc068826b272ac504e9960fd7727bc80c72c72)

[5.1.x] add reference to Spring Tettei Nyuumonn in introduction #2043

---

source/Introduction/CriteriaBasedMapping.rst

Fix and update mapping based on security measures #1893

---

source/Introduction/CriteriaBasedMapping.rst

Fix and update mapping based on security measures (5.1.x) #1893

---

source/Introduction/Introduction.rst

Please review #2118 .
I resolved problem that path `../ArchitectureInDetail/index` is output at PDF created.
__Backport for this PR is unnecessary.__ Because this problem has bean occured only in the master branch for `Optimize the order of chapters and sections`  #1683 .

Revise description of document constitution #2118

---

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst

Please review #2140.
This PR should be merged after updating to 5.3.0-SNAPSHOT.

Add YearTypeHandler and MonthTypeHandler into settings example #2140

---

source/ArchitectureInDetail/DataAccessDetail/DataAccessMyBatis3.rst

Please review #2140.
(cherry picked from commit 24ab8e34fd5031f37c610e32a3935bff10048c1c)
This PR should be merged after updating to 5.2.1-SNAPSHOT.

[5.2.x] Add YearTypeHandler and MonthTypeHandler into settings example #2140

---

source/Security/Authentication.rst

Add note for SessionAuthenticationStrategy #1961

---

source/Security/Authentication.rst

[5.2.x] Add note for SessionAuthenticationStrategy #1961

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py

Update version to 5.0.3-SNAPSHOT (fixed) #1690

---

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst

#1994 Reading BeanValidation message with Message Source

---

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst

[5.2.x]#1994 Reading BeanValidation message with Message Source for 5.2.x

---

source_en/ArchitectureInDetail/Validation.rst

[translation/5.1.1]#1994 Reading BeanValidation message with Message Source  for translation/5.1.1

---

source_en/ArchitectureInDetail/Validation.rst

[5.1.x]#1994 Reading BeanValidation message with Message Source for 5.1.x

---

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst

#1994 Reading BeanValidation message with Message Source for 5.3.0

---

source_en/ImplementationAtEachLayer/DomainLayer.rst

#2009 @transaction not used while using MyBatis3.3

---

source_en/Tutorial/TutorialTodo.rst

#2019 improving guideline for todo application tutorial

---

source_en/ImplementationAtEachLayer/DomainLayer.rst

Please review #2009 .
(cherry picked from commit 92ffab959a16f1e2215b99cc924ccd1a1e45597e)

[translation/5.1.1]#2009 @transaction not used while using MyBatis3.3
