source/ArchitectureInDetail/DataAccessCommon.rst
source_en/ArchitectureInDetail/DataAccessCommon.rst

Backported to 1.0.x from Please review  #714 .
Please review #713 .

[1.0.x] Removed the unnecessary description for escaping of wildcard search in DataAccessCommon.rst. #713

---

source/ArchitectureInDetail/Ajax.rst
source_en/ArchitectureInDetail/Ajax.rst

cherry-picked from #739 .
英語版の `<meta>` タグの修正は別issueで行います。一部masterの内容が取り込まれてしまっているので、それを直す時に一緒に修正します。
確認お願いします。 #680

[1.0.x] Modified meta tag's name for CSRF in Ajax.rst. #680

---

source_en/ArchitectureInDetail/Ajax.rst

Reverted description of  spring security 3.2(`<sec:csrfMetaTag>`) and applied meta tag's name of CSRF.
Please review #680 .

[1.0.x en] Modified meta tag's name for CSRF in Ajax.rst. #680

---

source/ArchitectureInDetail/FileUpload.rst
source_en/ArchitectureInDetail/FileUpload.rst

(cherry picked from commit e184f0a7b1a984d34318b6799fe4edaac37dfc2d)
Backport to 1.0.x.
Please review #846 .

[1.0.x] Modify wrong explanation of CVE-2014-0050. #846

---

source/ImplementationAtEachLayer/DomainLayer.rst

Spring Framework 4.1 + Hibernate 4.2 以上を組み合わせて使用した時に、`@Transactional(readOnly = true)`を指定すると`Connection#setReadOnly(true)`が呼び出せるように改善されたので、その内容を反映しました。
#482

Update the description of readOnly flag of @Transactional for JPA. #482

---

source/Appendix/Nexus.rst

(cherry picked from commit f18c2edef0947ef28f6a84c795978fb4a57bbcbf)
Backported from master branch.
Please review #923 (#922).

[5.0.x] fix typos in Nexus

---

source/index.rst
source_en/index.rst

(cherry picked from commit 849e4e82702147dcaa2a9611cce549db64c1cc80)
backported from master.
Please review #931 .

[1.0.x] #931: Improve link url for creating a new issue

---

source/index.rst
source_en/index.rst

(cherry picked from commit 849e4e82702147dcaa2a9611cce549db64c1cc80)
backported from master.
Please review #931 .

[5.0.x] #931: Improve link url for creating a new issue

---

source_en/ArchitectureInDetail/DataAccessJpa.rst

(cherry picked from commit d6aa6c82fd160cd425b8d719e94af8d50111a5e4)
Backported to 5.0.x.
Please review #941 .

[5.0.x] #941: Modify typo in DataAccessJpa.rst

---

source/ArchitectureInDetail/Utilities/Dozer.rst
source_en/ArchitectureInDetail/Utilities/Dozer.rst

定義名誤りを修正しました、確認をお願いします。5.0.x系へのバックポートです。
(cherry picked from commit b8e768a1643f3224be04dbc7d16cb198c49e8253)

fix guideline. #1074

---

source/Appendix/EnvironmentIndependency.rst

(cherry picked from commit 5fda429d13a015e8abfe3590da91308db84034d4)
I backport to 5.0.x.
Please review #1081 .

[5.0.x] #1081: Improve descriptions of how to deploy to the Tomcat

---

source/ArchitectureInDetail/SessionManagement.rst

(cherry picked from commit c8f8e3ed349451b11d73c46baf291ca5e960cf14)
I backport to 5.0.x.
Please review #1082 .

[5.0.x] #1082: Add a proxyMode attribute in sample code of Appendix

---

source/ArchitectureInDetail/Codelist.rst

* Improve indent of code-block and list-table
* Add inner link
(cherry picked from commit 06c0a229c5da9ebb30dff383e62176f4e6c4ab49)
I backport to 5.0.x.
Please review #1109 .

[5.0.x] #1109: Improve explanation of how to display a code name

---

source/Security/Authentication.rst

session-managementの閉じタグが二つあったので、不要な一つを削除。
ご確認をお願いいたします。 #940

fix typo about session-management #940

---

source_en/Security/Authentication.rst

session-managementの閉じタグが二つあるタイポの修正。
英語版の修正が漏れていたため、再度pull requestを作成致します。
よろしくお願いいたします。 #940

fix typo about session-management (in English) #940

---

source/Security/Authentication.rst
source_en/Security/Authentication.rst

(cherry picked from commit ea87e5d and 3549c00)
Please review #940.

[5.0.x]#940: fix typo session management

---

source/Overview/FrameworkStack.rst
source_en/Overview/FrameworkStack.rst

フレームワークスタック一覧中のUserTypeのRemarkが1(MyBatis3使用時に依存)となっていたので2(JPA使用時に依存)に修正。
ご確認をお願いいたします。 #976

fix typo about framework stack #976

---

source_en/ArchitectureInDetail/Codelist.rst

[5.0.x] #1109: Add explanation of how to display a code name in CodeList.rst (English translation)

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

[5.0.x] #977: Add explanation about additivity attribute in Logging chapter

---

source/ArchitectureInDetail/Validation.rst
source_en/ArchitectureInDetail/Validation.rst

(cherry picked from commit 07d377a55660bd2d2ffc122b267a090cf037a91f)
Please review #1029 .

[5.0.x] #1029: Fix wrong message definitions in Validation.rst

---

source_en/ArchitectureInDetail/DataAccessCommon.rst

#1237: Fix bad grammar in 'Escaping during LIKE search'

---

source_en/ArchitectureInDetail/DataAccessCommon.rst

(cherry picked from commit 28f6ac6a80bcbaa8e40c47ccc2fe4a0cf911f954)
Please review #1237 .

[5.0.x] #1237: Fix bad grammar in 'Escaping during LIKE search'

---

source/ArchitectureInDetail/Logging.rst
source_en/ArchitectureInDetail/Logging.rst

(cherry picked from commit f93c1e247bba05823357c73a37e7554b15c8cde0)
Please review #1274 .

[5.0.x] #1274: Fixes wrong configuration file name of logback

---

source/ArchitectureInDetail/MessageManagement.rst
source/ImplementationAtEachLayer/ApplicationLayer.rst
source_en/ArchitectureInDetail/MessageManagement.rst
source_en/ImplementationAtEachLayer/ApplicationLayer.rst

(cherry picked from commit 45809b86b4f8e902a71bfa506cd96fb403ff5d61)
Please review #1279 .

[5.0.x] #1279: Update links of Java SE JavaDoc to 8

---

source/ArchitectureInDetail/FileDownload.rst

[AbstractPdfViewがcom.lowagie:itext:4.2.1では使えない](https://github.com/terasolunaorg/guideline/issues/1310)
itextのバージョンをSpring IO Platformに準拠して変更

fix com.lowagie.itext version 4.2.1->2.1.7 #1310

---

source_en/ArchitectureInDetail/FileDownload.rst

[fix com.lowagie.itext version 4.2.1->2.1.7 #1310 #1334 ](https://github.com/terasolunaorg/guideline/pull/1334#discussion-diff-41479005)
について、英語版修正

Fix com.lowagie.itext version 4.2.1 -> 2.1.7 #1310

---

source/ArchitectureInDetail/Validation.rst

5.0.x系にバックポート致しました。
ご確認をよろしくお願いいたします。#1375 #1379 
(cherry picked from commit 65e45cb7f4666229da23087795cb4cc87128629a)

modify Ag to Age #1375

---

source/Security/Tutorial.rst

(cherry picked from commit 1de27e28d760963ae3ebff5736a071b6c6f27ecb)
Please review #1374 .

Fix typo in Spring Security Tutorial #1374

---

source/ArchitectureInDetail/Validation.rst
source_en/ArchitectureInDetail/Validation.rst

以下を修正しました。
* 制約アノテーション一覧のテーブル構成の修正（「用途」と「設定値」欄を「説明」欄に統合など）。
* タイプミスの修正
* 既存のアノテーション一覧にてインラインコードブロックを使うように修正
* 既存修正箇所を英語版にも反映 (翻訳は、新設部分のみが対象)
このPRでは、内容がかわるような変更は行っていません。
#1389 の確認お願いします。

Polishing Validation.rst #1389

---

source/ArchitectureInDetail/Validation.rst

I removed description of `@After` and `@Before` annotation, because I'd to removed them from terasoluna-gfw.
Related pull request is https://github.com/terasolunaorg/terasoluna-gfw/pull/407.
Please review #1389.

Remove description of @After and @Before annotation #1389

---

source/ArchitectureInDetail/Utilities/StringProcessing.rst

I've fixed wrong unicode notation ( `\\u` -> `\u` ).
Please review #1451 .

Fix wrong unicode notation #1451

---

source/ArchitectureInDetail/REST.rst

`ObjectMapper`を`Jackson2ObjectMapperFactoryBean`を使用して作成するように修正し、Noteとして`Jackson2ObjectMapperFactoryBean`の簡単な説明と使用時の注意点を記載しました。
また、JSR-310 Date and Time APIやJoda Timeなどのコアライブラリでサポートしていないクラスを扱う場合は、Data typeの拡張モジュール(`jackson-datatype-jsr310` や `jackson-datatype-joda` など)が必要なので、それらのライブラリを依存ライブラリに追加する方法もあわせて追加しました。
Please review #1022 .

Improve how to define ObjectMapper of Jackson #1022

---

source/ArchitectureInDetail/DataAccessJpa.rst
source_en/ArchitectureInDetail/DataAccessJpa.rst

(cherry picked from commit fc274690403d56ba2ed94bfabdfb415b522bc6cf)
Backport to 5.0.x
Please review #1464

[5.0.x] #1464 Modified the wrong utility

---

source/Security/Encryption.rst

@ikeyat , please review. #1562
I fixed two places.
One is in section 6.8.2.1.1, add description of gcm can be used in later jdk8.
And the other one is in section 6.8.2.2.1, add description of Base64.

add description of jdk8'class use #1562

---

source/ArchitectureInDetail/REST.rst

@ikeyat さん、5.1.0.RELEASEガイドラインPDFにおける目次内容の表示不具合に対応しました。 #1680
カラム数が誤っていた個所を修正したところ、目次が表示されるようになりました。
ご確認よろしくお願いします。

Modified index of PDF for 5.1.0.RELEASE guideline. #1680

---

source/ArchitectureInDetail/Internationalization.rst

Please review #1354 .
I counldn't cherry-pick automatically. I backported manually.
I reproduced commit  91d1f034a2826d5e42cc6165b983cab76bd0fd1c  /   9990e6d7f3c029825571a7151ea2e2b59eb9460a  /  91a08a4faa65a75c31b0ac2ff42328232b62ce2c

5.1.x_backport_Fix_Description_of_paramName_in_LocaleChangeInterceptor.#1354

---

source/ArchitectureInDetail/DataAccessMyBatis3.rst

Please review #1292 . 
(5.1.x Backport)
(cherry picked from commit 243e27cd1de2d3a1a63df334af18cf0ea53409ec)

#1292_Delete_note_SqlsessionTemplate_warn_log_controlled

---

source_en/ImplementationAtEachLayer/DomainLayer.rst

Please review #2009 .
(cherry picked from commit 92ffab959a16f1e2215b99cc924ccd1a1e45597e)

[5.3.x] #2009 @transaction not used while using MyBatis3.3

---

source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst
source_en/Introduction/ChangeLog.rst

Please review #2070.
rebase https://github.com/terasolunaorg/guideline/pull/2253
(cherry picked from commit feeea2f8bd8f9e95489ae73a6868f4957f6a8709)

[5.2.x] #2070 Added warnings for new vulnerabilities in commons file upload

---

source_en/ArchitectureInDetail/WebApplicationDetail/FileUpload.rst
source_en/Introduction/ChangeLog.rst

Please review #2070.
rebase https://github.com/terasolunaorg/guideline/pull/2256
(cherry picked from commit feeea2f8bd8f9e95489ae73a6868f4957f6a8709)

[5.3.x] #2070 Added warnings for new vulnerabilities in commons file upload

---

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst

(cherry picked from commit 8bd062b4379071537f16701ebb870711e6bb2b12)
Please review #2397 . Backport for 5.2.x .

「4.1.2.3.1. Spring Validatorによる相関項目チェック実装」の誤記 #2397

---

source/Overview/FirstApplication.rst
source/Tutorial/TutorialREST.rst
source/Tutorial/TutorialSecurity.rst
source/Tutorial/TutorialTodo.rst
source_en/Overview/FirstApplication.rst
source_en/Tutorial/TutorialREST.rst
source_en/Tutorial/TutorialSecurity.rst
source_en/Tutorial/TutorialTodo.rst

(cherry picked from commit de3e68a5319c0340e408e2b2db6c09d47b37c9e2)
Please review #2410 .

fix typo in sample of spring-mvc.xml. #2410

---

source/Security/Authorization.rst

:emphasize-lines: 2,3 の除去5.3.x対応版です。

[5.3.x]remove highlighting in spring-security.xml for authorization.#2399

---

source/Security/Authorization.rst

:emphasize-lines: 2,3 の除去5.2.x対応版です。

[5.2.x]remove highlighting in spring-security.xml for authorization.#2399

---

source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst

(cherry picked from commit e92ff039ecf7bcc69f669991f52a75a821b6456d)
Please review #2397 
fix for english version

「4.1.2.3.1. Spring Validatorによる相関項目チェック実装」の誤記  #2397 

---

source_en/ArchitectureInDetail/MessagingDetail/JMS.rst

(cherry picked from commit 4a125a633c2027d05cc3139aa91804f0d57447bd)
Please review #2153 .
Fix for english version.
backport for 5.2.x

[5.2.x] Typo in JMS section.  #2153

---

source_en/ArchitectureInDetail/WebServiceDetail/REST.rst
source_en/ArchitectureInDetail/WebServiceDetail/SOAP.rst

Please review #2490.
cherry picked from commit 9136513424e264afd63af8f051014bf9b6c68e33 50f699964ab6dceb1d0ae4942c0fe1198dd8f52a

fix wrong word context route to context root 5.2.x #2490

---

conf/html/conf.py
conf/html_for_githubpages/conf.py
conf/latexpdfen/conf.py
conf/latexpdfja/conf.py
theme/solar/layout.html
theme/solar_for_githubpages/layout.html

Please review #2628 .
本Issue対応に当たり、copyrightを２つ貼ることになった。
当初はSphinxの設定ファイル、conf.pyにおいてcopyrightを持つ変数を２つ持つことで対応しようとしたが、変数名をcopyrightから変更した場合（ex. copyright1）、layout.htmlで認識されないことが判明した。
そのため、２つのcopyrightを一つのconf.pyにあるcopyright変数に入れるために、表示される© Copyrightの部分もまとめてconf.pyのcopyright変数に入れることにした。
しかし、Layout.htmlは元々Sphinxのデフォルトのファイルを流用している。
そのため、© Copyrightの部分は、layout.htmlによって動的にリンクが貼られるようになっている。
しかし、conf.pyのcopyright変数には動的にリンクを貼ることは出来ない。
このため、guidelineの© Copyright部分にはリンクが貼られることはないことを確認した上で、今回の対応で、hasdoc()を使用してリンクを貼っている場所を削除した。

fix double copyright #2628

---

source_en/Security/Authorization.rst

(cherry picked from commit 6be6ca3d0f172404b9934418975237710214efd3)
Please review #2648.

#2685 backport for 5.2.1.

---

source/Tutorial/TutorialREST.rst

(cherry picked from commit 8ec70143c972a03f1853e4c6be74f01c04e1a5d1)
Please review #2281. Backport for 5.3.x.

[5.3.x] Delete ControllerAdvice annotation attribute. #2281

---

source/ImplementationAtEachLayer/CreateProject.rst
source_en/ImplementationAtEachLayer/CreateProject.rst

(cherry picked from commit c68663961e7814854d3ddc75efc8d8c6bbad4281)
Please review #2762. Backport for 5.3.x

[5.3.x] typo of caret at maven command. #2762

---

source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst

(cherry picked from commit 415eb2cb1e7ef60892a1d429554c4acbfc254d21 )
Please review #2824.  Backport for 5.3.1.

[5.3.1]Minor typos of Exception Name. #2824

---

source/Introduction/ChangeLog.rst

Please review #2717 #2847 .
Change logの順番をガイドラインの章・節の順にあわせるように修正。

[5.3.x] fix order of items in change log #2717 #2847

---

source/Introduction/ChangeLog.rst
source/Security/Authentication.rst

Please review #2092. Backport for 5.2.2.

[5.2.x] Add note for risk that plaintext passwords are described log. #2092

---

source/Introduction/ChangeLog.rst
source/Security/Authentication.rst

Please review #2092. Backport for 5.1.2.

[5.1.x] Add note for risk that plaintext passwords are described log. #2092

---

source/Introduction/ChangeLog.rst
source/Security/PasswordHashing.rst

Please review #2092. Backport for 5.0.3.

[5.0.x] Add note for risk that plaintext passwords are described log. #2092

---

source/Introduction/ChangeLog.rst
source/Security/PasswordHashing.rst

Please review #2092. Backport for 1.0.7.

[1.0.x] Add note for risk that plaintext passwords are described log. #2092

---

source/ArchitectureInDetail/WebApplicationDetail/Validation.rst
source_en/ArchitectureInDetail/WebApplicationDetail/Validation.rst

(cherry picked from commit a3076cf1d623719b62d08b64fd80c7c0998c0558)
Please review #2792 .
backport for 5.3.x.

[5.3.x]Validation - Explanation of group validation is incorrect.  #2792

---

source/Security/SecureLoginDemo.rst
source_en/Security/SecureLoginDemo.rst

(cherry picked from commit cabf57bc622c06a23a60d522b2722dfa20a80100)
I've backported to the 5.3.x branch.
Please review #2966.

[5.3.x] Improve some code of EncodedPasswordHistoryRule #2966

---

source/Security/OAuth.rst

(cherry picked from commit 4fb35a7a7eb6a5078e1fa0940a57276cafc33266)
Please review #3010 .
バックポートです。ご確認よろしくお願いいたします。

[5.3.x] Modify tabularcolumns #3010

---

source/Overview/FrameworkStack.rst

Please review #3064.
Maven Centralにterasoluna-gfw-common-librariesとterasoluna-gfw-dependenciesが存在するため
ブランクプロジェクト組込を「無」に変更する形で対応を行いました。
http://repo1.maven.org/maven2/org/terasoluna/gfw/terasoluna-gfw-common-libraries
http://repo1.maven.org/maven2/org/terasoluna/gfw/terasoluna-gfw-dependencies/

fix introduction status for libraries against blank project. #3064

---

source/Overview/FrameworkStack.rst

(cherry picked from commit cd3318be2d15331588ad70cf425a6bd949de25e1)
Please review #3064.
This PR is backport for 5.3.x

[5.3.x] fix introduction status for libraries against blank project. #3064

---

source/Overview/FrameworkStack.rst

(cherry picked from commit cd3318be2d15331588ad70cf425a6bd949de25e1)
Please review #3064.
This PR is backport for 5.2.x

[5.2.x] fix introduction status for libraries against blank project. #3064

---

source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst

(cherry picked from commit ef23af18a8e8a1a02257abf41ff643f3e92f87b8)
Please review #3234

[5.4.x] Fixed Typo in Codelist.rst

---

source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst

(cherry picked from commit f55f20b5f9f2999f74db0a478213c4dbd9f659b9)
Please review #3172 .
This PR is backport for 5.4.x .

[5.4.x] The TOC in TagLibAndELFunctions.rst has disappeared. #3172

---

source/Tutorial/TutorialREST.rst

Please review #3219 .
Correct error in description of package hierarchy happened at #3219 correspondense .

Correct error in description of package hierarchy #3219
